import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(process.cwd());
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const folderPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/Folder.page');
const folderJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.js');
const folderContractJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
const folderPreviewModelJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.preview-model.js');
const folderEditorSharedJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.shared.js');
const dockerJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.js');
const dockerPreviewActionsScript = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.preview-actions.js');
const sharedRuntimeJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.shared.js');
const dockerRuntimeHierarchyJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.hierarchy.js');
const dockerCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/docker.css');
const runtimeSharedCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/runtime.shared.css');
const serverLibPhp = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/server/lib.php');

test('folder editor exposes preview row limit control and persists the setting', () => {
    assert.match(folderPage, /<select name="preview_rows">/);
    assert.match(folderPage, /<option value="0"[^>]*>Unlimited<\/option>/);
    assert.match(folderPage, /<li constraint="preview-1 preview-2 preview-3 preview-4 docker">[\s\S]*<select name="preview_status">/);
    assert.match(folderPage, /<option value="none">Hide status<\/option>/);
    assert.match(folderPage, /name="preview_hide_nested_items"/);
    assert.match(folderPage, /Show child folders in collapsed preview:/);
    assert.match(folderPage, /name="preview_child_folder_depth"/);
    assert.match(folderPage, /Child folder preview depth:/);
    assert.match(folderPage, /id="fvFolderMembersSection"/);
    assert.match(folderPage, /id="fvFolderMembersBody"/);
    assert.match(folderPage, /Nested folders/);
    assert.match(folderPage, /<option value="1">Direct children only<\/option>/);
    assert.match(folderPage, /<option value="0">All nested folders<\/option>/);
    assert.match(folderContractJs, /const extractPreviewRowLimitValue = \(value,\s*fallbackSource = null\) =>/);
    assert.match(folderContractJs, /source\.preview_rows\s*\?\?\s*source\.previewRows/);
    assert.match(folderJs, /let folderEditorSharedApi = null;/);
    assert.match(folderJs, /const getFolderEditorSharedApi = \(\) =>/);
    assert.match(folderJs, /folderEditorSharedApi = folderEditorShared\.createApi\(/);
    assert.match(folderJs, /const normalizePreviewRowLimit = \(value,\s*fallbackSource = null\) =>/);
    assert.match(folderEditorSharedJs, /preview_rows:\s*normalizePreviewRowLimit\(settings,\s*source\)/);
    assert.match(folderJs, /if \(!Number\.isFinite\(parsed\)\) \{\s*return 1;\s*\}/);
    assert.match(folderJs, /setFieldValue\('preview_rows',\s*String\(normalizePreviewRowLimit\(normalizedFolder\.settings,\s*normalizedFolder\)\)\);/);
    assert.match(folderJs, /setFieldChecked\('preview_hide_nested_items', normalizedFolder\.settings\.preview_hide_nested_items\);/);
    assert.match(folderJs, /setFieldValue\('preview_child_folder_depth', String\(normalizeChildFolderPreviewDepth\(normalizedFolder\.settings, normalizedFolder\)\)\);/);
    assert.match(folderJs, /const normalizedPreviewRows = normalizePreviewRowLimit\(e\.preview_rows\?\.value\);/);
    assert.match(folderJs, /const normalizedChildFolderPreviewDepth = normalizeChildFolderPreviewDepth\(e\.preview_child_folder_depth\?\.value\);/);
    assert.match(folderJs, /preview_rows:\s*normalizedPreviewRows,/);
    assert.match(folderJs, /previewRows:\s*normalizedPreviewRows,/);
    assert.match(folderJs, /preview_hide_nested_items:\s*e\.preview_hide_nested_items\.checked,/);
    assert.match(folderJs, /child_folder_order:\s*getChildFolderOrderIds\(\),/);
    assert.match(folderJs, /childFolderOrder:\s*getChildFolderOrderIds\(\),/);
    assert.match(folderJs, /preview_child_folder_depth:\s*normalizedChildFolderPreviewDepth,/);
    assert.match(folderEditorSharedJs, /preview_hide_nested_items:\s*settings\.preview_hide_nested_items === true \|\| settings\.previewHideNestedItems === true/);
    assert.match(folderEditorSharedJs, /previewHideNestedItems:\s*settings\.preview_hide_nested_items === true \|\| settings\.previewHideNestedItems === true/);
    assert.match(folderEditorSharedJs, /child_folder_order:\s*normalizeChildFolderOrder\(settings\.child_folder_order \|\| settings\.childFolderOrder\)/);
    assert.match(folderEditorSharedJs, /childFolderOrder:\s*normalizeChildFolderOrder\(settings\.child_folder_order \|\| settings\.childFolderOrder\)/);
    assert.match(folderEditorSharedJs, /const normalizeChildFolderPreviewDepth = typeof deps\.normalizeChildFolderPreviewDepth === 'function'/);
    assert.match(folderEditorSharedJs, /preview_child_folder_depth:\s*normalizeChildFolderPreviewDepth\(settings, source\)/);
    assert.match(serverLibPhp, /\$rawPreviewHideNestedItems = \$normalized\['settings'\]\['preview_hide_nested_items'\]/);
    assert.match(serverLibPhp, /\$normalized\['settings'\]\['previewHideNestedItems'\] = \$normalized\['settings'\]\['preview_hide_nested_items'\];/);
    assert.match(serverLibPhp, /\$rawChildFolderOrder = \$normalized\['settings'\]\['child_folder_order'\]/);
    assert.match(serverLibPhp, /\$normalized\['settings'\]\['childFolderOrder'\] = \$childFolderOrder;/);
    assert.match(serverLibPhp, /\$rawPreviewChildFolderDepth = \$normalized\['settings'\]\['preview_child_folder_depth'\]/);
    assert.match(serverLibPhp, /\$normalized\['settings'\]\['previewChildFolderDepth'\] = \$normalizedDepth;/);
});

test('docker runtime applies preview row layout limits and keeps compact preview cards clickable', () => {
    assert.match(sharedRuntimeJs, /const getPreviewRowLimitValue = \(settings = \{\}\) =>/);
    assert.match(sharedRuntimeJs, /settings\?\.preview_rows\s*\?\?\s*settings\?\.previewRows/);
    assert.match(sharedRuntimeJs, /const normalizeFolderPreviewRowLimit = \(settings = \{\}\) =>/);
    assert.match(sharedRuntimeJs, /const isCompactMultiRowPreview = \(settings = \{\}\) =>/);
    assert.match(sharedRuntimeJs, /const applyFolderPreviewLayout = \(\$preview,\s*settings = \{\}\) =>/);
    assert.match(sharedRuntimeJs, /const flattenPreviewWrappers = \(\$preview\) =>/);
    assert.match(sharedRuntimeJs, /const restoreLinearPreviewLayout = \(\$preview,\s*settings = \{\}\) =>/);
    assert.match(sharedRuntimeJs, /const finalizePreviewRows = \(\$preview,\s*rowSlices = \[\],\s*settings = \{\}\) =>/);
    assert.match(dockerJs, /const getFolderPreviewItemsPerRow = \(settings = \{\}\) =>/);
    assert.match(dockerPreviewActionsScript, /const reconcileDockerPreviewActionButtons = \(\$target,[\s\S]*options = \{\}\) =>/);
    assert.match(dockerPreviewActionsScript, /ensureDockerPreviewActionSlot/);
    assert.match(dockerPreviewActionsScript, /data-fv-preview-action-slot/);
    assert.doesNotMatch(
        dockerPreviewActionsScript,
        /\$target\.children\('span\.folder-element-webui, span\.folder-element-console, span\.folder-element-logs/
    );
    assert.match(dockerJs, /const buildDockerPreviewItem = \(\{ entry = \{\}, settings = \{\}, autostart = false \}\) =>/);
    assert.match(dockerJs, /const shouldHidePreviewStatus = previewStatusMode === 'none';/);
    assert.match(dockerJs, /\['none', 'hide', 'hidden', 'off', 'false', '0', 'no'\]\.includes\(normalized\)/);
    assert.match(dockerJs, /const compactStatusMarkup = shouldHidePreviewStatus[\s\S]*\? ''[\s\S]*: `<span class="fv-preview-status-compact"/);
    assert.match(dockerJs, /const inlineStatusMarkup = shouldHidePreviewStatus[\s\S]*\? ''[\s\S]*: `<br>/);
    assert.match(dockerJs, /const bindCompactPreviewDefaultContext = \(\$item, \$sourceRow\) =>/);
    assert.match(dockerJs, /const buildCompactPreviewDefaultContextItem = \(\$sourceRow, settings = \{\}, autostart = false\) =>/);
    assert.match(dockerJs, /const \$sourceOuter = \$sourceRow\.find\('td\.ct-name > span\.outer'\)\.first\(\)/);
    assert.match(dockerJs, /const bindCompactPreviewDefaultContextProxy = \(\$item\) =>/);
    assert.match(dockerJs, /\$menuTrigger\.trigger\('click'\);/);
    assert.match(dockerJs, /\$sourceRow\.find\('td\.ct-name > span\.outer > span\.hand'\)\.first\(\)/);
    assert.match(dockerJs, /const inlineClick = String\(\$nativeTrigger\.attr\('onclick'\) \|\| ''\)\.trim\(\);/);
    assert.match(dockerJs, /const targets = \[/);
    assert.match(dockerJs, /\$target\.addClass\('hand'\);/);
    assert.match(dockerJs, /\$target\.attr\('onclick', inlineClick\);/);
    assert.match(dockerJs, /fv-docker-preview-mode-2 fv-preview-trigger fv-preview-tooltip-proxy/);
    assert.match(dockerJs, /fv-docker-preview-mode-\$\{previewMode\} fv-preview-trigger fv-preview-tooltip-proxy/);
    assert.match(dockerJs, /fv-docker-preview-mode-1 fv-preview-trigger fv-preview-tooltip-proxy/);
    assert.match(dockerJs, /fv-preview-trigger fv-preview-tooltip-proxy/);
    assert.match(dockerJs, /\$tooltipTrigger:\s*triggerSelector === '\.fv-docker-preview-card'\s*\?\s*\$compactItem/);
    assert.match(dockerJs, /const appendCompactPreview = \(folderTrId, ctid, autostart, previewEntry, \$sourceRow = null, options = \{\}\) =>/);
    assert.match(dockerJs, /if \(folder\.settings\.context === 1 && options\.preferNativeDefaultContext !== false\) \{/);
    assert.match(dockerJs, /compactPreviewItem = buildCompactPreviewDefaultContextItem\(\$sourceRow, folder\.settings, autostart\);/);
    assert.match(dockerJs, /bindCompactPreviewDefaultContextProxy\(\$item\);/);
    assert.match(dockerJs, /bindCompactPreviewDefaultContext\(\$item, \$sourceRow\);/);
    assert.match(dockerJs, /\$target\.data\('fvTooltipEnsureInitialized', ensureInitialized\);/);
    assert.match(dockerJs, /const layoutFolderPreviewRows = \(\$preview, settings = \{\}\) =>/);
    assert.match(dockerJs, /const applyFolderPreviewLayout = typeof dockerRuntimeShared\.applyFolderPreviewLayout === 'function'/);
    assert.match(dockerJs, /const flattenPreviewWrappers = typeof dockerRuntimeShared\.flattenPreviewWrappers === 'function'/);
    assert.match(dockerJs, /const restoreLinearPreviewLayout = typeof dockerRuntimeShared\.restoreLinearPreviewLayout === 'function'/);
    assert.match(dockerJs, /const finalizePreviewRows = typeof dockerRuntimeShared\.finalizePreviewRows === 'function'/);
    assert.match(dockerJs, /renderDockerSingleRowPreview\(/);
    assert.match(dockerJs, /resilientSingleRowPreview\(1, 'td\.ct-name > span\.outer'/);
    assert.match(dockerJs, /resilientSingleRowPreview\(3, 'td\.ct-name > span\.outer > span\.inner'/);
    assert.match(dockerPreviewActionsScript, /appendRequestBundleTrace\('single-row-preview-fallback'/);
    assert.doesNotMatch(dockerJs, /clone\.find\(`span\.state`\)\[0\]\.innerHTML/);
    assert.match(dockerPreviewActionsScript, /const cloneDockerSingleRowPreviewSource = \(\$sourceRow, selector, options = \{\}\) =>/);
    assert.match(dockerPreviewActionsScript, /reason: 'state-markup-missing'/);
    assert.match(dockerPreviewActionsScript, /reason: 'preview-markup-missing'/);
    assert.match(dockerJs, /\$previewElementTarget\.children\('span\.inner'\)\.last\(\)/);
    assert.match(dockerJs, /runDockerPreviewRenderer\(/);
    assert.match(dockerJs, /previewStatusMode !== 'none' && \(previewMode === 3 \|\| previewMode === 4\)/);
    assert.match(dockerRuntimeHierarchyJs, /const shouldHideNestedPreviewItems = \(settings = \{\}\) => settings\?\.preview_hide_nested_items === true/);
    assert.match(dockerRuntimeHierarchyJs, /const sortFolderChildren = \(parentId, childIds\) => \{/);
    assert.match(dockerRuntimeHierarchyJs, /parentSettings\.child_folder_order \|\| parentSettings\.childFolderOrder/);
    assert.match(dockerRuntimeHierarchyJs, /return sortFolderChildren\(folderId, Array\.isArray\(map\[folderId\]\) \? map\[folderId\] : \[\]\);/);
    assert.match(dockerRuntimeHierarchyJs, /const buildChildFolderPreviewItem = \(parentId, childId, childFolder, options = \{\}\) =>/);
    assert.match(dockerRuntimeHierarchyJs, /fv-docker-preview-card fv-docker-preview-mode-1 fv-folder-preview-child/);
    assert.match(dockerRuntimeHierarchyJs, /const normalizeChildFolderPreviewDepth = \(settings = \{\}\) => \{/);
    assert.match(dockerRuntimeHierarchyJs, /const getFolderPreviewDescendants = \(folderId, maxDepth = 0\) => \{/);
    assert.match(dockerRuntimeHierarchyJs, /if \(maxDepth > 0 && depth >= maxDepth\) \{/);
    assert.match(dockerRuntimeHierarchyJs, /result\.push\(\{ id: safeChildId, depth \}\);/);
    assert.match(dockerRuntimeHierarchyJs, /visit\(safeChildId, depth \+ 1\);/);
    assert.match(dockerRuntimeHierarchyJs, /const expandFolderPathToChild = \(rootId, childId\) => \{/);
    assert.match(dockerRuntimeHierarchyJs, /const ancestors = getFolderAncestors\(safeChildId\)\.reverse\(\);/);
    assert.match(dockerRuntimeHierarchyJs, /dropDownButton\(pathId, false\);/);
    assert.match(dockerRuntimeHierarchyJs, /const getFolderBreadcrumb = \(folderId\) => \{/);
    assert.ok(dockerRuntimeHierarchyJs.includes("breadcrumb.join(' / ')"));
    assert.match(folderPreviewModelJs, /const formatRuntimeCountLabel = \(startedCount, memberCount\) => \{/);
    assert.match(dockerRuntimeHierarchyJs, /previewModelModule\.createChildFolderPreviewModel\(\{/);
    assert.match(dockerRuntimeHierarchyJs, /runtimeCountLabel/);
    assert.match(dockerRuntimeHierarchyJs, /const showFolderPreviewContextMenu = \(event, rootId, childId, childName\) => \{/);
    assert.match(dockerRuntimeHierarchyJs, /addAction\('Expand to folder', 'fa-level-down'/);
    assert.match(dockerRuntimeHierarchyJs, /addAction\('Edit folder', 'fa-pencil'/);
    assert.match(dockerRuntimeHierarchyJs, /addAction\('Open folder actions', 'fa-bars'/);
    assert.match(dockerRuntimeHierarchyJs, /addAction\('Open folder actions', 'fa-bars', \(\) => \{[\s\S]*expandFolderPathToChild\(rootId, childId\);[\s\S]*scrollFolderRowIntoView\(childId\);[\s\S]*openFolderActions\(childId\);/);
    assert.match(dockerRuntimeHierarchyJs, /data-folder-preview-root/);
    assert.match(dockerRuntimeHierarchyJs, /data-folder-preview-child/);
    assert.match(dockerRuntimeHierarchyJs, /data-folder-preview-depth/);
    assert.match(dockerRuntimeHierarchyJs, /includeChildFolders\s*:\s*shouldHideNestedPreviewItems\(folder\?\.settings \|\| \{\}\)/);
    assert.match(dockerRuntimeHierarchyJs, /buildRuntimeContainerMapForFolder\(id, false\)/);
    assert.match(dockerRuntimeHierarchyJs, /const depthLimit = normalizeChildFolderPreviewDepth\(folder\?\.settings \|\| \{\}\);/);
    assert.match(dockerRuntimeHierarchyJs, /for \(const descendant of getFolderPreviewDescendants\(id, depthLimit\)\)/);
    assert.doesNotMatch(dockerRuntimeHierarchyJs, /for \(const childId of getFolderChildren\(id\)\) \{[\s\S]*buildChildFolderPreviewItem\(id, childId, childFolder\)/);
    assert.match(dockerRuntimeHierarchyJs, /expandFolderPathToChild\(parentId, childId\);/);
    assert.match(dockerJs, /editFolder: \(id\) => editFolder\(id\)/);
    assert.match(dockerJs, /openFolderActions: \(id\) => \{/);
    assert.match(dockerJs, /const trigger = document\.getElementById\(String\(id \|\| ''\)\.trim\(\)\);/);
    assert.match(dockerJs, /const rect = typeof trigger\.getBoundingClientRect === 'function'/);
    assert.match(dockerJs, /const clientX = rect \? rect\.left \+ Math\.max\(1, rect\.width \/ 2\) : 0;/);
    assert.match(dockerJs, /const clientY = rect \? rect\.top \+ Math\.max\(1, rect\.height \/ 2\) : 0;/);
    assert.match(dockerJs, /trigger\.dispatchEvent\(new MouseEvent\('click'/);
    assert.match(dockerJs, /clientX,\s*[\r\n]+\s*clientY/);
    assert.match(dockerJs, /addDockerFolderContext\(id\);/);
    assert.match(dockerJs, /const maxItemsPerRow = Math\.max\(1,\s*getFolderPreviewItemsPerRow\(settings\)\)/);
    assert.match(dockerJs, /const \$measurement = availableWidth > 0/);
    assert.match(dockerJs, /fv-preview-multirow fv-preview-row-measure/);
    assert.match(dockerJs, /\.appendTo\(document\.body\)/);
    assert.match(dockerJs, /flexDirection:\s*'row'/);
    assert.match(dockerJs, /const measurementWrappers = wrappers\.map\(\(wrapper,\s*index\) =>/);
    assert.match(dockerJs, /const wrapperTop = Number\(measurementWrapper\?\.offsetTop \?\? 0\)/);
    assert.match(dockerJs, /const startsNewRow = currentRow\.length > 0/);
    assert.match(dockerJs, /const exceedsItemCap = currentRow\.length >= maxItemsPerRow/);
    assert.match(dockerJs, /restoreLinearPreviewLayout\(\$preview,\s*settings\);/);
    assert.match(dockerJs, /const wrappers = flattenPreviewWrappers\(\$preview\);/);
    assert.match(dockerJs, /finalizePreviewRows\(\$preview,\s*visibleRows,\s*settings\);/);
    assert.match(dockerJs, /layoutFolderPreviewRows\(\$\(`tr\.folder-id-\$\{id\} div\.folder-preview`\), folder\.settings\)/);
    assert.match(dockerRuntimeHierarchyJs, /layoutFolderPreviewRows\(\$preview, folder\?\.settings \|\| \{\}\)/);
    assert.match(dockerJs, /decorateDockerFolderMemberRow\(\$containerTR, id, ct\.info\.Name \|\| container_name_in_folder\)/);
    assert.match(dockerJs, /decorateDockerPreviewMemberTriggers\(/);
    assert.match(dockerJs, /\.removeClass\('fv-docker-member-menu-trigger'\)/);
    assert.match(dockerJs, /\.removeAttr\('data-folder-id'\)/);
    assert.match(dockerJs, /\.removeAttr\('data-container-name'\)/);
    assert.match(dockerJs, /\.off\('click\.fvDockerMemberMenuTrigger'\)/);
    assert.match(dockerJs, /\.off\('click\.fvDockerMemberMenuAction'\)/);
    assert.match(dockerJs, /\.off\('click\.fvDockerPreviewTooltipProxy'\)/);
    assert.match(dockerJs, /\.off\('click\.fvDockerPreviewActionFallback'\)/);
    assert.match(dockerJs, /\.on\('click\.fvDockerPreviewTooltipProxy', '\.fv-preview-tooltip-proxy', function\(event\) \{/);
    assert.match(dockerJs, /\.on\('click\.fvDockerPreviewActionFallback', '\.folder-preview \.folder-element-webui > a, \.folder-preview \.folder-element-console > a, \.folder-preview \.folder-element-logs > a', function\(event\) \{/);
    assert.match(dockerJs, /const \$trigger = \$proxy\.closest\('\[id\^="folder-preview-"\]'\);/);
    assert.match(dockerJs, /const ensureInitialized = \$trigger\.data\('fvTooltipEnsureInitialized'\);/);
    assert.match(dockerJs, /const tooltipInitialized = \$trigger\.data\('fvTooltipsterInitialized'\) === true;/);
    assert.match(dockerJs, /if \(typeof ensureInitialized === 'function' && tooltipInitialized !== true\) \{/);
    assert.match(dockerJs, /ensureInitialized\('click'\);/);
    assert.match(dockerJs, /if \(tooltipInitialized === true\) \{/);
    assert.match(dockerJs, /\$trigger\.tooltipster\('open'\);/);
    assert.match(dockerJs, /const action = String\(\$link\.attr\('data-fv-preview-action'\) \|\| ''\)\.trim\(\)\.toLowerCase\(\);/);
    assert.match(dockerJs, /openWebuiInNewTab\(webuiUrl\);/);
    assert.match(dockerJs, /openTerminal\('docker', containerName, shellValue\);/);
    assert.doesNotMatch(dockerJs, /FolderViewDockerPreviewMemberMenu/);
    assert.doesNotMatch(dockerJs, /showDockerPreviewMemberMenu/);
    assert.match(dockerPreviewActionsScript, /\.attr\('data-fv-preview-action', 'webui'\)/);
    assert.match(dockerPreviewActionsScript, /const hideDockerPreviewStatus = \(\$target\) => \{/);
    assert.match(dockerPreviewActionsScript, /\['none', 'hide', 'hidden', 'off', 'false', '0', 'no'\]\.includes\(normalized\)/);
    assert.match(dockerPreviewActionsScript, /if \(previewStatusMode === 'none'\) \{[\s\S]*hideDockerPreviewStatus\(\$target\);[\s\S]*\} else \{[\s\S]*syncDockerPreviewStatus\(\$target, entry\);/);
    assert.match(dockerPreviewActionsScript, /\.attr\('data-webui-url', webuiUrl\)/);
    assert.match(dockerPreviewActionsScript, /\.attr\('data-fv-preview-action', 'console'\)/);
    assert.match(dockerPreviewActionsScript, /\.attr\('data-container-name', containerName\)/);
    assert.match(dockerPreviewActionsScript, /\.attr\('data-shell-value', shellValue\)/);
    assert.match(dockerPreviewActionsScript, /\.attr\('data-fv-preview-action', 'logs'\)/);
    assert.match(dockerPreviewActionsScript, /\.attr\('data-shell-value', '\.log'\)/);
    assert.match(dockerPreviewActionsScript, /event\.preventDefault\(\);\s*event\.stopPropagation\(\);\s*openWebuiInNewTab\(webuiUrl\);/s);
    assert.match(dockerPreviewActionsScript, /event\.preventDefault\(\);\s*event\.stopPropagation\(\);\s*openTerminal\('docker',\s*containerName,\s*shellValue\);/s);
    assert.match(dockerPreviewActionsScript, /event\.preventDefault\(\);\s*event\.stopPropagation\(\);\s*openTerminal\('docker',\s*containerName,\s*'\.log'\);/s);
});

test('docker styles support multi-row previews without the removed member action sheet styling', () => {
    assert.match(dockerCss, /\.hover:hover div\.folder-preview div:not\(\.folder-preview-row\):not\(\.folder-preview-divider\) \{/);
    assert.match(dockerCss, /\.hover div\.folder-preview div:not\(\.folder-preview-row\):not\(\.folder-preview-divider\) \{/);
    assert.doesNotMatch(dockerCss, /td\.folder-preview-cell > \.folder-preview:not\(\.fv-preview-multirow\) \{/);
    assert.match(runtimeSharedCss, /\.folder-preview \{/);
    assert.match(runtimeSharedCss, /\.folder-preview \{[\s\S]*align-items:\s*center/);
    assert.match(runtimeSharedCss, /\.folder-preview \{[\s\S]*flex-wrap:\s*wrap/);
    assert.match(runtimeSharedCss, /\.folder-preview \{[\s\S]*align-content:\s*flex-start/);
    assert.match(dockerCss, /\.folder-preview-row \{/);
    assert.match(dockerCss, /\.folder-preview-row \{[\s\S]*align-items:\s*flex-start/);
    assert.match(dockerCss, /\.folder-preview-row \{[\s\S]*column-gap:\s*0/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \{/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \{[\s\S]*row-gap:\s*2px/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \{[\s\S]*padding:\s*2px 0/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{[\s\S]*align-items:\s*center/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{[\s\S]*justify-content:\s*flex-start/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{[\s\S]*min-height:\s*var\(--fvplus-preview-row-height\)/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{[\s\S]*padding:\s*0/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-wrapper \{/);
    assert.match(runtimeSharedCss, /\.folder-preview-wrapper \{[\s\S]*margin-left:\s*10px/);
    assert.match(runtimeSharedCss, /\.folder-preview-wrapper \{[\s\S]*margin-top:\s*var\(--fvplus-preview-wrapper-margin-top,\s*6px\)/);
    assert.match(runtimeSharedCss, /\.folder-preview-wrapper \{[\s\S]*flex:\s*0 0 auto/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-wrapper \{[\s\S]*min-height:\s*calc\(var\(--fvplus-preview-row-height\) - 0\.9em\)/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-wrapper \{[\s\S]*margin:\s*6px 0 0 10px/);
    assert.doesNotMatch(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-wrapper \{[\s\S]*transform:\s*translateY\(/);
    assert.match(dockerCss, /\.folder-preview-divider \{/);
    assert.match(dockerCss, /\.folder-preview-divider \{[\s\S]*align-self:\s*stretch/);
    assert.match(dockerCss, /\.folder-preview-divider \{[\s\S]*min-height:\s*calc\(var\(--fvplus-preview-row-height\) - 1\.2em\)/);
    assert.match(dockerCss, /\.folder-preview-divider \{[\s\S]*margin:\s*0\.35em 0 0\.35em 6px/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-divider \{/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-divider \{[\s\S]*align-self:\s*center/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-divider \{[\s\S]*height:\s*1\.35em/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-divider \{[\s\S]*margin:\s*0 0 0 6px/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.fv-docker-preview-card \{/);
    assert.match(dockerCss, /\.folder-preview \.fv-preview-action-slot \{/);
    assert.match(dockerCss, /\.folder-preview \.fv-preview-action-slot\.is-pending,[\s\S]*visibility:\s*hidden/);
    assert.match(dockerCss, /\.folder-preview \.fv-preview-webui-placeholder-icon \{/);
    assert.match(dockerCss, /\.folder-preview \.fv-folder-preview-child \{/);
    assert.match(dockerCss, /\.folder-preview \.fv-folder-preview-child-icon \{[\s\S]*width:\s*36px/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.fv-folder-preview-child-icon \{[\s\S]*width:\s*28px/);
    assert.match(dockerCss, /\.folder-preview \.fv-folder-preview-child-count \{/);
    assert.match(dockerCss, /\.fv-folder-preview-context-menu \{/);
    assert.match(dockerCss, /\.fv-folder-preview-context-menu \{[\s\S]*gap:\s*0/);
    assert.match(dockerCss, /\.fv-folder-preview-context-menu button \{/);
    assert.match(dockerCss, /\.fv-folder-preview-context-menu button \{[\s\S]*font-size:\s*0\.86em/);
    assert.match(dockerCss, /\.fv-folder-preview-context-menu button \{[\s\S]*height:\s*22px/);
    assert.match(dockerCss, /\.fv-folder-preview-context-menu button \{[\s\S]*margin:\s*0/);
    assert.match(dockerCss, /\.fv-docker-preview-mode-1 \{/);
    assert.doesNotMatch(dockerCss, /\.fv-docker-member-menu-trigger/);
    assert.doesNotMatch(dockerCss, /\.fv-docker-member-menu-actions/);
    assert.doesNotMatch(dockerCss, /\.fv-docker-member-menu-action/);
    assert.doesNotMatch(dockerCss, /tr\.folder > td\[colspan\]/);
});
