import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(process.cwd());
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const folderPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/Folder.page');
const folderJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.js');
const dockerJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.js');
const dockerMemberMenuJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.member-menu.js');
const dockerCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/docker.css');

test('folder editor exposes preview row limit control and persists the setting', () => {
    assert.match(folderPage, /<select name="preview_rows">/);
    assert.match(folderPage, /<option value="0">Unlimited<\/option>/);
    assert.match(folderJs, /const extractPreviewRowLimitValue = \(value,\s*fallbackSource = null\) =>/);
    assert.match(folderJs, /source\.preview_rows\s*\?\?\s*source\.previewRows/);
    assert.match(folderJs, /const normalizePreviewRowLimit = \(value,\s*fallbackSource = null\) =>/);
    assert.match(folderJs, /if \(!Number\.isFinite\(parsed\)\) \{\s*return 1;\s*\}/);
    assert.match(folderJs, /preview_rows:\s*normalizePreviewRowLimit\(settings,\s*source\)/);
    assert.match(folderJs, /setFieldValue\('preview_rows',\s*String\(normalizePreviewRowLimit\(normalizedFolder\.settings,\s*normalizedFolder\)\)\);/);
    assert.match(folderJs, /const normalizedPreviewRows = normalizePreviewRowLimit\(e\.preview_rows\?\.value\);/);
    assert.match(folderJs, /preview_rows:\s*normalizedPreviewRows,/);
    assert.match(folderJs, /previewRows:\s*normalizedPreviewRows,/);
});

test('docker runtime applies preview row layout limits and enhanced member action menus', () => {
    assert.match(dockerJs, /const getPreviewRowLimitValue = \(settings = \{\}\) =>/);
    assert.match(dockerJs, /settings\?\.preview_rows\s*\?\?\s*settings\?\.previewRows/);
    assert.match(dockerJs, /const normalizeFolderPreviewRowLimit = \(settings = \{\}\) =>/);
    assert.match(dockerJs, /const getFolderPreviewItemsPerRow = \(settings = \{\}\) =>/);
    assert.match(dockerJs, /const shouldRenderPreviewWebuiPlaceholder = \(settings = \{\}, webuiQuickActionEnabled = false\) =>/);
    assert.match(dockerJs, /settings\?\.preview_vertical_bars === true/);
    assert.match(dockerJs, /const appendPreviewWebuiPlaceholder = \(\$target\) =>/);
    assert.match(dockerJs, /fv-preview-webui-placeholder/);
    assert.match(dockerJs, /const buildDockerPreviewItem = \(\{ entry = \{\}, settings = \{\}, autostart = false \}\) =>/);
    assert.match(dockerJs, /const applyFolderPreviewLayout = \(\$preview, settings = \{\}\) =>/);
    assert.match(dockerJs, /const layoutFolderPreviewRows = \(\$preview, settings = \{\}\) =>/);
    assert.match(dockerJs, /let clone = \$\(`tr\.folder-id-\$\{folderTrId\} div\.folder-storage > tr > td\.ct-name > span\.outer:last`\)\.clone\(\)/);
    assert.match(dockerJs, /\$previewElementTarget\.children\('span\.inner'\)\.last\(\)/);
    assert.match(dockerJs, /const maxItemsPerRow = Math\.max\(1,\s*getFolderPreviewItemsPerRow\(settings\)\)/);
    assert.match(dockerJs, /const \$measurement = availableWidth > 0/);
    assert.match(dockerJs, /fv-preview-multirow fv-preview-row-measure/);
    assert.match(dockerJs, /\.appendTo\(document\.body\)/);
    assert.match(dockerJs, /flexDirection:\s*'row'/);
    assert.match(dockerJs, /const measurementWrappers = wrappers\.map\(\(wrapper,\s*index\) =>/);
    assert.match(dockerJs, /const wrapperTop = Number\(measurementWrapper\?\.offsetTop \?\? 0\)/);
    assert.match(dockerJs, /const startsNewRow = currentRow\.length > 0/);
    assert.match(dockerJs, /const exceedsItemCap = currentRow\.length >= maxItemsPerRow/);
    assert.match(dockerJs, /layoutFolderPreviewRows\(\$\(`tr\.folder-id-\$\{id\} div\.folder-preview`\), folder\.settings\)/);
    assert.match(dockerJs, /layoutFolderPreviewRows\(\$preview, folder\?\.settings \|\| \{\}\)/);
    assert.match(dockerJs, /decorateDockerFolderMemberRow\(\$containerTR, id, ct\.info\.Name \|\| container_name_in_folder\)/);
    assert.match(dockerJs, /decorateDockerPreviewMemberTriggers\(/);
    assert.match(dockerJs, /dockerPreviewMemberMenuModule\.createController\(/);
    assert.match(dockerJs, /const showDockerPreviewMemberMenu = \(entry\) =>/);
    assert.match(dockerMemberMenuJs, /\.on\('click\.fvDockerMemberMenuTrigger', '\.fv-docker-member-menu-trigger'/);
    assert.match(dockerMemberMenuJs, /const eventUrl = String\(deps\.eventURL \|\| win\.eventURL \|\| ''\)\.trim\(\);/);
    assert.match(dockerMemberMenuJs, /const bindMenu = \(\) =>/);
    assert.match(dockerMemberMenuJs, /const shouldSuppressPreviewMemberMenu = \(entry\) =>/);
    assert.match(dockerMemberMenuJs, /const contextMode = Number\(folder\?\.settings\?\.context \?\? -1\);/);
    assert.match(dockerMemberMenuJs, /const contextTrigger = Number\(folder\?\.settings\?\.context_trigger \?\? 0\);/);
    assert.match(dockerMemberMenuJs, /return contextMode === 2 && contextTrigger !== 1;/);
    assert.match(dockerMemberMenuJs, /if \(shouldSuppressPreviewMemberMenu\(entry\)\) \{\s*return;\s*\}/);
});

test('docker styles support multi-row previews and member action sheet styling', () => {
    assert.match(dockerCss, /\.hover:hover div\.folder-preview div:not\(\.folder-preview-row\):not\(\.folder-preview-divider\) \{/);
    assert.match(dockerCss, /\.hover div\.folder-preview div:not\(\.folder-preview-row\):not\(\.folder-preview-divider\) \{/);
    assert.match(dockerCss, /\.folder-preview \{/);
    assert.match(dockerCss, /\.folder-preview \{[\s\S]*align-items:\s*center/);
    assert.match(dockerCss, /\.folder-preview \{[\s\S]*flex-wrap:\s*wrap/);
    assert.match(dockerCss, /\.folder-preview \{[\s\S]*align-content:\s*flex-start/);
    assert.match(dockerCss, /\.folder-preview-row \{/);
    assert.match(dockerCss, /\.folder-preview-row \{[\s\S]*align-items:\s*flex-start/);
    assert.match(dockerCss, /\.folder-preview-row \{[\s\S]*column-gap:\s*0/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \{/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \{[\s\S]*row-gap:\s*2px/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \{[\s\S]*padding:\s*2px 0/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{[\s\S]*align-items:\s*center/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{[\s\S]*justify-content:\s*flex-start/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{[\s\S]*min-height:\s*var\(--fvplus-preview-row-height\)/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-row \{[\s\S]*padding:\s*0/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-wrapper \{/);
    assert.match(dockerCss, /\.folder-preview-wrapper \{[\s\S]*margin-left:\s*10px/);
    assert.match(dockerCss, /\.folder-preview-wrapper \{[\s\S]*margin-top:\s*6px/);
    assert.match(dockerCss, /\.folder-preview-wrapper \{[\s\S]*flex:\s*0 0 auto/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-wrapper \{[\s\S]*min-height:\s*calc\(var\(--fvplus-preview-row-height\) - 0\.9em\)/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-wrapper \{[\s\S]*margin:\s*6px 0 0 10px/);
    assert.doesNotMatch(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-wrapper \{[\s\S]*transform:\s*translateY\(/);
    assert.match(dockerCss, /\.folder-preview-divider \{/);
    assert.match(dockerCss, /\.folder-preview-divider \{[\s\S]*align-self:\s*stretch/);
    assert.match(dockerCss, /\.folder-preview-divider \{[\s\S]*min-height:\s*calc\(var\(--fvplus-preview-row-height\) - 1\.2em\)/);
    assert.match(dockerCss, /\.folder-preview-divider \{[\s\S]*margin:\s*0\.35em 0 0\.35em 6px/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-divider \{/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-divider \{[\s\S]*align-self:\s*center/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-divider \{[\s\S]*height:\s*1\.35em/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.folder-preview-divider \{[\s\S]*margin:\s*0 0 0 6px/);
    assert.match(dockerCss, /\.folder-preview\.fv-preview-multirow \.fv-docker-preview-card \{/);
    assert.match(dockerCss, /\.folder-preview \.fv-preview-webui-placeholder \{/);
    assert.match(dockerCss, /\.folder-preview \.fv-preview-webui-placeholder \{[\s\S]*visibility:\s*hidden/);
    assert.match(dockerCss, /\.folder-preview \.fv-preview-webui-placeholder-icon \{/);
    assert.match(dockerCss, /\.fv-docker-preview-mode-1 \{/);
    assert.match(dockerCss, /\.fv-docker-member-menu-trigger/);
    assert.match(dockerCss, /\.fv-docker-member-menu-actions/);
    assert.match(dockerCss, /\.fv-docker-member-menu-action/);
    assert.doesNotMatch(dockerCss, /tr\.folder > td\[colspan\]/);
});
