import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(process.cwd());
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const dockerPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/folderview.plus.Docker.page');
const folderContractJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
const dockerSharedJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.shared.js');
const dockerModulesJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.modules.js');
const dockerJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.js');
const dockerCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/docker.css');
const runtimeSharedCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/runtime.shared.css');

test('docker runtime page loads shared runtime module before docker modules/runtime', () => {
    const fatalBannerIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.fatal-banner.js');
    const contractIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
    const sharedIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.shared.js');
    const stateObserverIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/folder.runtime.state-observers.js');
    const modulesIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.modules.js');
    const runtimeIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.js');
    const sharedCssIndex = dockerPage.indexOf('/plugins/folderview.plus/styles/runtime.shared.css');
    const dockerCssIndex = dockerPage.indexOf('/plugins/folderview.plus/styles/docker.css');
    assert.ok(fatalBannerIndex >= 0, 'docker page should load the shared fatal banner runtime');
    assert.ok(contractIndex >= 0, 'shared folder contract include is missing');
    assert.ok(sharedIndex >= 0, 'shared runtime script include is missing');
    assert.ok(stateObserverIndex >= 0, 'runtime state observer script include is missing');
    assert.ok(modulesIndex >= 0, 'docker modules script include is missing');
    assert.ok(runtimeIndex >= 0, 'docker runtime script include is missing');
    assert.ok(sharedCssIndex >= 0, 'shared runtime stylesheet include is missing');
    assert.ok(dockerCssIndex >= 0, 'docker stylesheet include is missing');
    assert.equal(dockerPage.includes('/plugins/folderview.plus/scripts/docker.member-menu.js'), false, 'docker member menu script include should be removed');
    assert.match(dockerPage, /window\.FolderViewPlusFatalRuntimeContext = \{/);
    assert.match(dockerPage, /page:\s*'Docker'/);
    assert.match(dockerPage, /hostSelector:\s*'\.canvas,\s*#fvplus-docker-runtime-banner-host'/);
    assert.match(dockerPage, /<div id="fvplus-docker-runtime-banner-host" aria-live="polite"><\/div>/);
    assert.ok(fatalBannerIndex < contractIndex, 'docker fatal banner must load before folder contract/runtime scripts');
    assert.ok(contractIndex < sharedIndex, 'shared contract must load before docker.runtime.shared.js');
    assert.ok(sharedIndex < modulesIndex, 'shared runtime must load before docker.modules.js');
    assert.ok(sharedIndex < stateObserverIndex, 'shared runtime must load before runtime state observer module');
    assert.ok(stateObserverIndex < runtimeIndex, 'runtime state observer module must load before docker.js');
    assert.ok(sharedIndex < runtimeIndex, 'shared runtime must load before docker.js');
    assert.ok(sharedCssIndex < dockerCssIndex, 'shared runtime stylesheet must load before docker.css');
});

test('docker shared runtime module binds to the shared folder contract and exports runtime primitives', () => {
    assert.match(dockerSharedJs, /^\/\/ @ts-check/m);
    assert.match(folderContractJs, /window\.FolderViewPlusFolderContract = \{/);
    assert.match(dockerSharedJs, /const folderContract = window\.FolderViewPlusFolderContract \|\| null;/);
    assert.match(dockerSharedJs, /folderContract\?\.DEFAULT_PREVIEW_BORDER_COLOR \|\| '#afa89e'/);
    assert.match(dockerSharedJs, /const extractDropdownStyleValue = typeof folderContract\?\.extractDropdownStyleValue === 'function'/);
    assert.match(dockerSharedJs, /const normalizeDropdownStyle = typeof folderContract\?\.normalizeDropdownStyle === 'function'/);
    assert.match(dockerSharedJs, /const getDropdownStyleTokens = typeof folderContract\?\.getDropdownStyleTokens === 'function'/);
    assert.match(dockerSharedJs, /const createRuntimeStateStore =/);
    assert.match(dockerSharedJs, /const createDebugLogger = \(enabled = false, namespace = 'folderview\.plus'\) =>/);
    assert.match(dockerSharedJs, /const createAsyncActionBoundary =/);
    assert.match(dockerSharedJs, /const createContextMenuQuickStripAdapter =/);
    assert.match(dockerSharedJs, /const createRuntimePerfTelemetry =/);
    assert.match(dockerSharedJs, /const createSafeUiActionRunner =/);
    assert.match(dockerSharedJs, /const resolveRuntimePerformanceProfile =/);
    assert.match(dockerSharedJs, /const createRuntimeDiagnosticsBridge = \(options = \{\}\) =>/);
    assert.match(dockerSharedJs, /const applyFolderDropdownStyle =/);
    assert.match(dockerSharedJs, /const runtimeContracts = Object\.freeze\(/);
    assert.match(dockerSharedJs, /window\.FolderViewDockerRuntimeShared =/);
});

test('docker runtime consumes shared state store and guarded async action wrappers', () => {
    assert.match(dockerJs, /const dockerRuntimeShared = window\.FolderViewDockerRuntimeShared \|\| \{\};/);
    assert.match(dockerJs, /const fatalBanner = window\.FolderViewPlusFatalBanner \|\| null;/);
    assert.match(dockerJs, /const DOCKER_FATAL_BANNER_HOST_SELECTOR = String\(dockerFatalBannerRuntimeConfig\.hostSelector \|\| '\.canvas, #fvplus-docker-runtime-banner-host'\)/);
    assert.match(dockerJs, /const createDockerRuntimeDiagnosticsBridge = typeof dockerRuntimeShared\.createRuntimeDiagnosticsBridge === 'function'/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('folderviewplus\.utils\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('folderviewplus\.request\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('docker\.runtime\.shared\.js'\)/);
    assert.match(dockerJs, /const reportDockerBootstrapDependencyBanner = \(missingModules\) =>/);
    assert.match(dockerJs, /const reportDockerFatalRuntimeError = \(error, options = \{\}\) =>/);
    assert.match(dockerJs, /const reportDockerDegradedRuntimeState = \(error, options = \{\}\) =>/);
    assert.match(dockerJs, /const createDockerRuntimeRequest = \(url, options = \{\}\) =>/);
    assert.match(dockerJs, /FolderView Plus Docker runtime bootstrap failed/);
    assert.match(dockerJs, /reportDockerBootstrapDependencyBanner\(dockerBootstrapMissingModules\);/);
    assert.match(dockerJs, /const runtimeStateObserverModule = window\.FolderViewPlusRuntimeStateObservers \|\| null;/);
    assert.match(dockerJs, /dockerRuntimeShared\.createDebugLogger/);
    assert.match(dockerJs, /const dockerRuntimeStateStore = createDockerRuntimeStateStore\(/);
    assert.match(dockerJs, /const dockerActionBoundary = createDockerAsyncActionBoundary\(/);
    assert.match(dockerJs, /const dockerExpandedStateController = runtimeStateObserverModule/);
    assert.match(dockerJs, /const dockerRuntimeThemeReflowController = runtimeStateObserverModule/);
    assert.match(dockerJs, /\.off\('click\.fvDockerMemberMenuTrigger'\)/);
    assert.match(dockerJs, /\.off\('click\.fvDockerMemberMenuAction'\)/);
    assert.doesNotMatch(dockerJs, /FolderViewDockerPreviewMemberMenu/);
    assert.match(dockerJs, /const runDockerGuardedAction = async \(actionName, action, context = \{\}\) =>/);
    assert.match(dockerJs, /window\.getDockerRuntimePerfTelemetrySnapshot =/);
    assert.match(dockerJs, /window\.hideAllTips = hideAllTips;/);
    assert.match(dockerJs, /window\.addDockerFolderContext = addDockerFolderContext;/);
    assert.match(dockerJs, /window\.dropDownButton = dropDownButton;/);
    assert.match(dockerJs, /window\.editFolder = editFolder;/);
    assert.match(dockerJs, /window\.forceUpdateFolder = forceUpdateFolder;/);
    assert.match(dockerJs, /window\.updateFolder = updateFolder;/);
    assert.match(dockerJs, /window\.createFolderBtn = createFolderBtn;/);
});

test('docker CSS keeps docker-specific layout tokens while shared stylesheet owns shared dropdown geometry', () => {
    assert.match(dockerCss, /--fvplus-docker-folder-right-gutter:\s*28px/);
    assert.match(dockerCss, /--fvplus-docker-folder-outer-reserved-width:\s*106px/);
    assert.match(dockerCss, /--fvplus-docker-folder-dropdown-right-margin:\s*16px/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-right-margin:\s*var\(--fvplus-docker-folder-dropdown-right-margin,\s*16px\)/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-icon-size:\s*12px/);
    assert.match(dockerCss, /--fvplus-preview-wrapper-margin-top:\s*6px/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-color:\s*#ff9a3c/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-hover-color:\s*#ff9a3c/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-hover-bg:\s*rgba\(255,\s*154,\s*60,\s*0\.18\)/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-min-width:\s*12px/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-radius:\s*5px/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-shadow:\s*inset 0 0 0 1px rgba\(255,\s*255,\s*255,\s*0\.05\), 0 1px 3px rgba\(0,\s*0,\s*0,\s*0\.18\)/);
    assert.match(dockerCss, /right:\s*var\(--fvplus-docker-folder-right-gutter,\s*28px\)/);
    assert.match(dockerCss, /max-width:\s*calc\(var\(--fvplus-docker-app-column-width\)\s*-\s*var\(--fvplus-docker-folder-outer-reserved-width,\s*106px\)\)/);
    assert.doesNotMatch(dockerCss, /^\.folder-dropdown\s*\{/m);
    assert.match(runtimeSharedCss, /margin:\s*0 var\(--fvplus-folder-dropdown-right-margin,\s*16px\) 0 auto/);
    assert.match(runtimeSharedCss, /border:\s*var\(--fvplus-folder-dropdown-border-width,\s*1px\) solid var\(--fvplus-folder-dropdown-border-color/);
    assert.match(runtimeSharedCss, /background:\s*var\(--fvplus-folder-dropdown-bg,\s*rgba\(255,\s*154,\s*60,\s*0\.1\)\) !important;/);
    assert.match(runtimeSharedCss, /\.folder-dropdown:hover,\s*[\s\S]*visibility:\s*visible !important/);
    assert.match(runtimeSharedCss, /\.folder-dropdown:hover > i,\s*[\s\S]*opacity:\s*1 !important/);
    assert.match(dockerCss, /border-right:\s*var\(--fvplus-preview-divider-width,\s*1px\) solid/);
});

test('docker folder row centering keeps the legacy flex layout and clears host bottom margin drift', () => {
    assert.match(dockerCss, /\.folder-name-sub\s*\{[\s\S]*display:\s*flex/);
    assert.match(dockerCss, /td\.ct-name\.folder-name > \.folder-name-sub > \.folder-outer\s*\{[\s\S]*margin-bottom:\s*0 !important/);
    assert.match(dockerModulesJs, /sub\.style\.setProperty\('display', 'flex', 'important'\);/);
    assert.match(dockerModulesJs, /sourceRows\.forEach\(\(row\) => \{[\s\S]*applyRowHeight\(row, 0\);[\s\S]*applyFolderCellCentering\(cell, 0\);/);
    assert.doesNotMatch(dockerModulesJs, /sourceRows\.forEach\(\(row\) => \{[\s\S]*getRenderedRowHeight\(row\);/);
});
