import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(process.cwd());
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const dockerPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/folderview.plus.Docker.page');
const folderContractJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
const dockerSharedJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.shared.js');
const dockerModulesJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.modules.js');
const dockerRuntimeInfoJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.info.js');
const dockerPreviewActionsJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.preview-actions.js');
const dockerRuntimeHierarchyJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.hierarchy.js');
const dockerRuntimeActionsJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.actions.js');
const dockerRuntimeHostGuardsJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.host-guards.js');
const dockerRuntimeDiagnosticsJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.diagnostics.js');
const dockerRuntimeReconcileJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.runtime.reconcile.js');
const dockerJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.js');
const dockerCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/docker.css');
const runtimeSharedCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/runtime.shared.css');

test('docker runtime page loads shared runtime module before docker modules/runtime', () => {
    const fatalBannerIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.fatal-banner.js');
    const contractIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
    const sharedIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.shared.js');
    const stateObserverIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/folder.runtime.state-observers.js');
    const modulesIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.modules.js');
    const runtimeInfoIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.info.js');
    const previewActionsIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.preview-actions.js');
    const runtimeHierarchyIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.hierarchy.js');
    const runtimeActionsIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.actions.js');
    const hostGuardsIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.host-guards.js');
    const diagnosticsIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.diagnostics.js');
    const reconcileIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.reconcile.js');
    const runtimeIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.js');
    const sharedCssIndex = dockerPage.indexOf('/plugins/folderview.plus/styles/runtime.shared.css');
    const dockerCssIndex = dockerPage.indexOf('/plugins/folderview.plus/styles/docker.css');
    assert.ok(fatalBannerIndex >= 0, 'docker page should load the shared fatal banner runtime');
    assert.ok(contractIndex >= 0, 'shared folder contract include is missing');
    assert.ok(sharedIndex >= 0, 'shared runtime script include is missing');
    assert.ok(stateObserverIndex >= 0, 'runtime state observer script include is missing');
    assert.ok(modulesIndex >= 0, 'docker modules script include is missing');
    assert.ok(runtimeInfoIndex >= 0, 'docker runtime info script include is missing');
    assert.ok(previewActionsIndex >= 0, 'docker preview actions script include is missing');
    assert.ok(runtimeHierarchyIndex >= 0, 'docker hierarchy script include is missing');
    assert.ok(runtimeActionsIndex >= 0, 'docker actions script include is missing');
    assert.ok(hostGuardsIndex >= 0, 'docker host guards script include is missing');
    assert.ok(diagnosticsIndex >= 0, 'docker diagnostics script include is missing');
    assert.ok(reconcileIndex >= 0, 'docker reconcile script include is missing');
    assert.ok(runtimeIndex >= 0, 'docker runtime script include is missing');
    assert.ok(sharedCssIndex >= 0, 'shared runtime stylesheet include is missing');
    assert.ok(dockerCssIndex >= 0, 'docker stylesheet include is missing');
    assert.equal(dockerPage.includes('/plugins/folderview.plus/scripts/docker.member-menu.js'), false, 'docker member menu script include should be removed');
    assert.match(dockerPage, /window\.FolderViewPlusFatalRuntimeContext = \{/);
    assert.match(dockerPage, /page:\s*'Docker'/);
    assert.match(dockerPage, /hostSelector:\s*'#fvplus-docker-runtime-banner-host,\s*\.canvas'/);
    assert.match(dockerPage, /<div id="fvplus-docker-runtime-banner-host" aria-live="polite"><\/div>/);
    assert.ok(fatalBannerIndex < contractIndex, 'docker fatal banner must load before folder contract/runtime scripts');
    assert.ok(contractIndex < sharedIndex, 'shared contract must load before docker.runtime.shared.js');
    assert.ok(sharedIndex < modulesIndex, 'shared runtime must load before docker.modules.js');
    assert.ok(sharedIndex < stateObserverIndex, 'shared runtime must load before runtime state observer module');
    assert.ok(modulesIndex < runtimeInfoIndex, 'docker.modules.js must load before docker.runtime.info.js');
    assert.ok(runtimeInfoIndex < previewActionsIndex, 'docker.runtime.info.js must load before docker.runtime.preview-actions.js');
    assert.ok(previewActionsIndex < runtimeHierarchyIndex, 'docker preview action helpers must load before docker.runtime.hierarchy.js');
    assert.ok(runtimeHierarchyIndex < runtimeActionsIndex, 'docker hierarchy helpers must load before docker.runtime.actions.js');
    assert.ok(runtimeActionsIndex < hostGuardsIndex, 'docker action helpers must load before docker.runtime.host-guards.js');
    assert.ok(hostGuardsIndex < diagnosticsIndex, 'docker host guards must load before docker.runtime.diagnostics.js');
    assert.ok(diagnosticsIndex < reconcileIndex, 'docker diagnostics helpers must load before docker.runtime.reconcile.js');
    assert.ok(reconcileIndex < runtimeIndex, 'docker reconcile helpers must load before docker.js');
    assert.ok(stateObserverIndex < runtimeIndex, 'runtime state observer module must load before docker.js');
    assert.ok(sharedIndex < runtimeIndex, 'shared runtime must load before docker.js');
    assert.ok(sharedCssIndex < dockerCssIndex, 'shared runtime stylesheet must load before docker.css');
});

test('docker extracted helper modules export createApi entry points with safe global fallbacks', () => {
    assert.match(dockerRuntimeInfoJs, /^\/\/ @ts-check/m);
    assert.match(dockerRuntimeInfoJs, /const fallbackWindow = typeof globalThis !== 'undefined'/);
    assert.match(dockerRuntimeInfoJs, /root\.FolderViewPlusDockerRuntimeInfo = factory\(\);/);
    assert.match(dockerRuntimeInfoJs, /root\.FolderViewPlusDockerRuntimeInfoModuleLoaded = true;/);
    assert.match(dockerRuntimeInfoJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(dockerPreviewActionsJs, /^\/\/ @ts-check/m);
    assert.match(dockerPreviewActionsJs, /const fallbackWindow = typeof globalThis !== 'undefined'/);
    assert.match(dockerPreviewActionsJs, /root\.FolderViewPlusDockerPreviewActions = factory\(\);/);
    assert.match(dockerPreviewActionsJs, /root\.FolderViewPlusDockerPreviewActionsModuleLoaded = true;/);
    assert.match(dockerPreviewActionsJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(dockerRuntimeHierarchyJs, /^\/\/ @ts-check/m);
    assert.match(dockerRuntimeHierarchyJs, /const fallbackWindow = typeof globalThis !== 'undefined'/);
    assert.match(dockerRuntimeHierarchyJs, /root\.FolderViewPlusDockerRuntimeHierarchy = factory\(\);/);
    assert.match(dockerRuntimeHierarchyJs, /root\.FolderViewPlusDockerRuntimeHierarchyModuleLoaded = true;/);
    assert.match(dockerRuntimeHierarchyJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(dockerRuntimeActionsJs, /^\/\/ @ts-check/m);
    assert.match(dockerRuntimeActionsJs, /const fallbackWindow = typeof globalThis !== 'undefined'/);
    assert.match(dockerRuntimeActionsJs, /root\.FolderViewPlusDockerRuntimeActions = factory\(\);/);
    assert.match(dockerRuntimeActionsJs, /root\.FolderViewPlusDockerRuntimeActionsModuleLoaded = true;/);
    assert.match(dockerRuntimeActionsJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(dockerRuntimeHostGuardsJs, /^\/\/ @ts-check/m);
    assert.match(dockerRuntimeHostGuardsJs, /const fallbackWindow = typeof globalThis !== 'undefined'/);
    assert.match(dockerRuntimeHostGuardsJs, /root\.FolderViewPlusDockerHostGuards = factory\(fallbackWindow\);/);
    assert.match(dockerRuntimeHostGuardsJs, /root\.FolderViewPlusDockerHostGuardsModuleLoaded = true;/);
    assert.match(dockerRuntimeHostGuardsJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(dockerRuntimeDiagnosticsJs, /^\/\/ @ts-check/m);
    assert.match(dockerRuntimeDiagnosticsJs, /const fallbackWindow = typeof globalThis !== 'undefined'/);
    assert.match(dockerRuntimeDiagnosticsJs, /root\.FolderViewPlusDockerRuntimeDiagnostics = factory\(fallbackWindow\);/);
    assert.match(dockerRuntimeDiagnosticsJs, /root\.FolderViewPlusDockerRuntimeDiagnosticsModuleLoaded = true;/);
    assert.match(dockerRuntimeDiagnosticsJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(dockerRuntimeReconcileJs, /^\/\/ @ts-check/m);
    assert.match(dockerRuntimeReconcileJs, /const fallbackWindow = typeof globalThis !== 'undefined'/);
    assert.match(dockerRuntimeReconcileJs, /root\.FolderViewPlusDockerRuntimeReconcile = factory\(fallbackWindow\);/);
    assert.match(dockerRuntimeReconcileJs, /root\.FolderViewPlusDockerRuntimeReconcileModuleLoaded = true;/);
    assert.match(dockerRuntimeReconcileJs, /const createApi = \(deps = \{\}\) =>/);
});

test('docker shared runtime module binds to the shared folder contract and exports runtime primitives', () => {
    assert.match(dockerSharedJs, /^\/\/ @ts-check/m);
    assert.match(folderContractJs, /window\.FolderViewPlusFolderContract = \{/);
    assert.match(dockerSharedJs, /const folderContract = window\.FolderViewPlusFolderContract \|\| null;/);
    assert.match(dockerSharedJs, /folderContract\?\.DEFAULT_PREVIEW_BORDER_COLOR \|\| '#afa89e'/);
    assert.match(dockerSharedJs, /const extractDropdownStyleValue = typeof folderContract\?\.extractDropdownStyleValue === 'function'/);
    assert.match(dockerSharedJs, /const normalizeDropdownStyle = typeof folderContract\?\.normalizeDropdownStyle === 'function'/);
    assert.match(dockerSharedJs, /const getDropdownStyleTokens = typeof folderContract\?\.getDropdownStyleTokens === 'function'/);
    assert.match(dockerSharedJs, /const createRuntimeStateStore =/);
    assert.match(dockerSharedJs, /const createDebugLogger = \(enabled = false, namespace = 'folderview\.plus'\) =>/);
    assert.match(dockerSharedJs, /const createAsyncActionBoundary =/);
    assert.match(dockerSharedJs, /const createContextMenuQuickStripAdapter =/);
    assert.match(dockerSharedJs, /const createRuntimePerfTelemetry =/);
    assert.match(dockerSharedJs, /const createSafeUiActionRunner =/);
    assert.match(dockerSharedJs, /const resolveRuntimePerformanceProfile =/);
    assert.match(dockerSharedJs, /const createRuntimeDiagnosticsBridge = \(options = \{\}\) =>/);
    assert.doesNotMatch(dockerSharedJs, /const createRuntimeCommandCenterController = \(options = \{\}\) =>/);
    assert.doesNotMatch(dockerSharedJs, /const alignHostToTable = \(host,\s*table\) =>/);
    assert.match(dockerSharedJs, /const applyFolderDropdownStyle =/);
    assert.match(dockerSharedJs, /const runtimeContracts = Object\.freeze\(/);
    assert.match(dockerSharedJs, /window\.FolderViewDockerRuntimeShared =/);
});

test('docker runtime consumes shared state store and guarded async action wrappers', () => {
    assert.match(dockerJs, /const dockerRuntimeShared = window\.FolderViewDockerRuntimeShared \|\| \{\};/);
    assert.match(dockerJs, /const dockerRuntimeInfoModule = window\.FolderViewPlusDockerRuntimeInfo \|\| null;/);
    assert.match(dockerJs, /const dockerPreviewActionsModule = window\.FolderViewPlusDockerPreviewActions \|\| null;/);
    assert.match(dockerJs, /const dockerRuntimeHierarchyModule = window\.FolderViewPlusDockerRuntimeHierarchy \|\| null;/);
    assert.match(dockerJs, /const dockerRuntimeActionsModule = window\.FolderViewPlusDockerRuntimeActions \|\| null;/);
    assert.match(dockerJs, /const dockerHostGuardsModule = window\.FolderViewPlusDockerHostGuards \|\| null;/);
    assert.match(dockerJs, /const dockerRuntimeDiagnosticsModule = window\.FolderViewPlusDockerRuntimeDiagnostics \|\| null;/);
    assert.match(dockerJs, /const dockerRuntimeReconcileModule = window\.FolderViewPlusDockerRuntimeReconcile \|\| null;/);
    assert.match(dockerJs, /const fatalBanner = window\.FolderViewPlusFatalBanner \|\| null;/);
    assert.match(dockerJs, /const DOCKER_FATAL_BANNER_HOST_SELECTOR = String\(dockerFatalBannerRuntimeConfig\.hostSelector \|\| '#fvplus-docker-runtime-banner-host, \.canvas'\)/);
    assert.match(dockerJs, /const createDockerRuntimeDiagnosticsBridge = typeof dockerRuntimeShared\.createRuntimeDiagnosticsBridge === 'function'/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('folderviewplus\.utils\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('folderviewplus\.request\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('docker\.runtime\.shared\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('docker\.runtime\.info\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('docker\.runtime\.preview-actions\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('docker\.runtime\.hierarchy\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('docker\.runtime\.actions\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('docker\.runtime\.host-guards\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('docker\.runtime\.diagnostics\.js'\)/);
    assert.match(dockerJs, /dockerBootstrapMissingModules\.push\('docker\.runtime\.reconcile\.js'\)/);
    assert.match(dockerJs, /const getDockerHostGuardsApi = \(\) => \{/);
    assert.match(dockerJs, /dockerHostGuardsModule\.createApi\(\{/);
    assert.match(dockerJs, /const getDockerRuntimeDiagnosticsApi = \(\) => \{/);
    assert.match(dockerJs, /dockerRuntimeDiagnosticsModule\.createApi\(\{/);
    assert.match(dockerJs, /const getDockerRuntimeReconcileApi = \(\) => \{/);
    assert.match(dockerJs, /dockerRuntimeReconcileModule\.createApi\(\{/);
    assert.match(dockerJs, /const buildDockerDiagnosticsCorrelationContext = \(\) => \(\{/);
    assert.match(dockerJs, /const getDockerRuntimeInfoApi = \(\) => \{/);
    assert.match(dockerJs, /dockerRuntimeInfoModule\.createApi\(\{/);
    assert.match(dockerJs, /const getDockerPreviewActionsApi = \(\) => \{/);
    assert.match(dockerJs, /dockerPreviewActionsModule\.createApi\(\{/);
    assert.match(dockerJs, /const getDockerRuntimeHierarchyApi = \(\) => \{/);
    assert.match(dockerJs, /dockerRuntimeHierarchyModule\.createApi\(\{/);
    assert.match(dockerJs, /const getDockerRuntimeActionsApi = \(\) => \{/);
    assert.match(dockerJs, /dockerRuntimeActionsModule\.createApi\(\{/);
    assert.match(dockerJs, /const syncDockerHostRowUpdateStatesFromDom = \(names = \[\]\) => \{[\s\S]*runtimeInfoApi\.syncDockerHostRowUpdateStatesFromDom\(names\)/);
    assert.match(dockerJs, /const ensureDockerHostRowUpdateObserver = \(\) => \{[\s\S]*runtimeInfoApi\.ensureDockerHostRowUpdateObserver\(\)/);
    assert.match(dockerJs, /const normalizeDockerRuntimeInfoMap = \(source,\s*previousMap = null\) => \{[\s\S]*runtimeInfoApi\.normalizeDockerRuntimeInfoMap\(source,\s*previousMap\)/);
    assert.match(dockerJs, /const appendDockerPreviewActionButtons = \(\$target,\s*settings = \{\},\s*containerName = '',\s*shellValue = '\/bin\/sh',\s*webuiUrl = ''\) => \{[\s\S]*previewActionsApi\.appendDockerPreviewActionButtons\(/);
    assert.match(dockerJs, /const syncDockerLeafFolderPreviewActions = \(id,\s*folder,\s*runtimeContainers\) => \{[\s\S]*previewActionsApi\.syncDockerLeafFolderPreviewActions\(id,\s*folder,\s*runtimeContainers\)/);
    assert.match(dockerJs, /const applyNestedFolderHierarchy = \(\) => \{[\s\S]*hierarchyApi\.applyNestedFolderHierarchy\(\);/);
    assert.match(dockerJs, /const dropDownButton = \(id,\s*persistState = true\) => \{[\s\S]*hierarchyApi\.dropDownButton\(id,\s*persistState\);/);
    assert.match(dockerJs, /const summarizeFolderActionCounts = \(containersMap\) => \{[\s\S]*actionsApi\.summarizeFolderActionCounts\(containersMap\)/);
    assert.match(dockerJs, /const rmFolder = \(id\) => \{[\s\S]*actionsApi\.rmFolder\(id\);/);
    assert.match(dockerJs, /const cloneDockerFolderBranchFromMenu = async \(id\) => \{[\s\S]*actionsApi\.cloneDockerFolderBranchFromMenu\(id\);/);
    assert.match(dockerJs, /const actionFolder = async \(id,\s*action,\s*\{ includeDescendants = true \} = \{\}\) => \{[\s\S]*actionsApi\.actionFolder\(id,\s*action,\s*\{ includeDescendants \}\);/);
    assert.match(dockerJs, /const reportDockerBootstrapDependencyBanner = \(missingModules\) =>/);
    assert.match(dockerJs, /const reportDockerFatalRuntimeError = \(error, options = \{\}\) =>/);
    assert.match(dockerJs, /const reportDockerDegradedRuntimeState = \(error, options = \{\}\) =>/);
    assert.match(dockerJs, /const createDockerRuntimeRequest = \(url, options = \{\}\) =>/);
    assert.match(dockerJs, /FolderView Plus Docker runtime bootstrap failed/);
    assert.match(dockerJs, /reportDockerBootstrapDependencyBanner\(dockerBootstrapMissingModules\);/);
    assert.match(dockerJs, /const runtimeStateObserverModule = window\.FolderViewPlusRuntimeStateObservers \|\| null;/);
    assert.match(dockerJs, /dockerRuntimeShared\.createDebugLogger/);
    assert.match(dockerJs, /const dockerRuntimeStateStore = createDockerRuntimeStateStore\(/);
    assert.match(dockerJs, /const dockerActionBoundary = createDockerAsyncActionBoundary\(/);
    assert.match(dockerJs, /const dockerExpandedStateController = runtimeStateObserverModule/);
    assert.match(dockerJs, /const dockerRuntimeThemeReflowController = runtimeStateObserverModule/);
    assert.match(dockerJs, /\.off\('click\.fvDockerMemberMenuTrigger'\)/);
    assert.match(dockerJs, /\.off\('click\.fvDockerMemberMenuAction'\)/);
    assert.doesNotMatch(dockerJs, /FolderViewDockerPreviewMemberMenu/);
    assert.match(dockerJs, /const runDockerGuardedAction = async \(actionName, action, context = \{\}\) =>/);
    assert.doesNotMatch(dockerJs, /createDockerRuntimeCommandCenterController/);
    assert.doesNotMatch(dockerJs, /syncDockerCommandCenterView/);
    assert.doesNotMatch(dockerJs, /data-fvplus-docker-view-mode/);
    assert.doesNotMatch(dockerJs, /data-fv-docker-command-action="create-folder"/);
    assert.match(dockerJs, /window\.getDockerRuntimePerfTelemetrySnapshot =/);
    assert.match(dockerJs, /window\.hideAllTips = hideAllTips;/);
    assert.match(dockerJs, /window\.addDockerFolderContext = addDockerFolderContext;/);
    assert.match(dockerJs, /window\.dropDownButton = dropDownButton;/);
    assert.match(dockerJs, /window\.editFolder = editFolder;/);
    assert.match(dockerJs, /window\.forceUpdateFolder = forceUpdateFolder;/);
    assert.match(dockerJs, /window\.updateFolder = updateFolder;/);
    assert.match(dockerJs, /window\.createFolderBtn = createFolderBtn;/);
});

test('docker CSS keeps docker-specific layout tokens while shared stylesheet owns shared dropdown geometry', () => {
    assert.match(dockerCss, /--fvplus-docker-folder-right-gutter:\s*28px/);
    assert.match(dockerCss, /--fvplus-docker-folder-outer-reserved-width:\s*106px/);
    assert.match(dockerCss, /--fvplus-docker-folder-dropdown-right-margin:\s*16px/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-right-margin:\s*var\(--fvplus-docker-folder-dropdown-right-margin,\s*16px\)/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-icon-size:\s*12px/);
    assert.match(dockerCss, /--fvplus-preview-wrapper-margin-top:\s*6px/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-color:\s*#ff9a3c/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-hover-color:\s*#ff9a3c/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-hover-bg:\s*rgba\(255,\s*154,\s*60,\s*0\.18\)/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-min-width:\s*12px/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-radius:\s*5px/);
    assert.match(dockerCss, /--fvplus-folder-dropdown-shadow:\s*inset 0 0 0 1px rgba\(255,\s*255,\s*255,\s*0\.05\), 0 1px 3px rgba\(0,\s*0,\s*0,\s*0\.18\)/);
    assert.match(dockerCss, /right:\s*var\(--fvplus-docker-folder-right-gutter,\s*28px\)/);
    assert.match(dockerCss, /max-width:\s*calc\(var\(--fvplus-docker-app-column-width\)\s*-\s*var\(--fvplus-docker-folder-outer-reserved-width,\s*106px\)\)/);
    assert.doesNotMatch(dockerCss, /^\.folder-dropdown\s*\{/m);
    assert.match(runtimeSharedCss, /margin:\s*0 var\(--fvplus-folder-dropdown-right-margin,\s*16px\) 0 auto/);
    assert.match(runtimeSharedCss, /border:\s*var\(--fvplus-folder-dropdown-border-width,\s*1px\) solid var\(--fvplus-folder-dropdown-border-color/);
    assert.match(runtimeSharedCss, /background:\s*var\(--fvplus-folder-dropdown-bg,\s*rgba\(255,\s*154,\s*60,\s*0\.1\)\) !important;/);
    assert.match(runtimeSharedCss, /\.folder-dropdown:hover,\s*[\s\S]*visibility:\s*visible !important/);
    assert.match(runtimeSharedCss, /\.folder-dropdown:hover > i,\s*[\s\S]*opacity:\s*1 !important/);
    assert.doesNotMatch(runtimeSharedCss, /\.fv-runtime-command-center\s*\{/);
    assert.doesNotMatch(runtimeSharedCss, /\.fv-runtime-command-center-grid\s*\{/);
    assert.doesNotMatch(runtimeSharedCss, /\.fv-runtime-command-card\s*\{/);
    assert.doesNotMatch(runtimeSharedCss, /\.fv-runtime-command-actions > button\[disabled\]/);
    assert.match(dockerCss, /border-right:\s*var\(--fvplus-preview-divider-width,\s*1px\) solid/);
});

test('docker folder row centering keeps the legacy flex layout and clears host bottom margin drift', () => {
    assert.match(dockerCss, /\.folder-name-sub\s*\{[\s\S]*display:\s*flex/);
    assert.match(dockerCss, /td\.ct-name\.folder-name > \.folder-name-sub > \.folder-outer\s*\{[\s\S]*margin-bottom:\s*0 !important/);
    assert.match(dockerModulesJs, /sub\.style\.setProperty\('display', 'flex', 'important'\);/);
    assert.match(dockerModulesJs, /sourceRows\.forEach\(\(row\) => \{[\s\S]*applyRowHeight\(row, 0\);[\s\S]*applyFolderCellCentering\(cell, 0\);/);
    assert.doesNotMatch(dockerModulesJs, /sourceRows\.forEach\(\(row\) => \{[\s\S]*getRenderedRowHeight\(row\);/);
});
