import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const folderJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.js');
const dockerJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.js');
const vmJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/vm.js');
const dashboardJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/dashboard.js');
const folderPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/Folder.page');
const folderEditorChromeJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.chrome.js');

test('folder editor runtime accepts query and hash bootstrap identity fallbacks', () => {
    assert.match(folderJs, /const readFolderEditorBootstrapSeed = \(\) =>/);
    assert.match(folderJs, /const readWindowNameFolderEditorBootstrapSeed = \(\) =>/);
    assert.match(folderJs, /const readCookieFolderEditorBootstrapSeed = \(\) =>/);
    assert.match(folderJs, /const EDITOR_DEBUG_BOOTSTRAP_STORAGE_KEY = 'fv\.folder\.editor\.debug\.bootstrap\.v1';/);
    assert.match(folderJs, /const recordFolderEditorBootstrapDebug = \(details = \{\}\) =>/);
    assert.match(folderJs, /const buildFolderEditorRefCandidates = \(\.\.\.values\) => Array\.from\(new Set/);
    assert.match(folderJs, /folderEditorBootstrapSeed\?\.type/);
    assert.match(folderJs, /folderEditorBootstrapSeed\?\.id/);
    assert.match(folderJs, /folderEditorBootstrapSeed\?\.folder/);
    assert.match(folderJs, /const folderEditorCookieBootstrap = readCookieFolderEditorBootstrapSeed\(\);/);
    assert.match(folderJs, /const folderEditorBootstrapSeed = folderEditorWindowNameBootstrap \|\| folderEditorStorageBootstrap \|\| folderEditorCookieBootstrap;/);
    assert.match(folderJs, /routeTargetRecovered: details\.routeTargetRecovered === true,/);
    assert.match(folderJs, /routeTargetMismatch: details\.routeTargetMismatch === true/);
    assert.match(folderJs, /const folderEditorHashParams = new URLSearchParams/);
    assert.match(folderJs, /const normalizedExpectedType = String\(expectedType \|\| ''\)\.trim\(\);/);
    assert.match(folderJs, /if \(normalizedExpectedType && normalizedType !== normalizedExpectedType\) \{/);
    assert.match(folderJs, /folderEditorHashParams\.get\('type'\)/);
    assert.match(folderJs, /folderEditorHashParams\.get\('id'\)/);
    assert.match(folderJs, /folderThemeSurfaceBinding\?\.runApply\('chrome-ready'\)/);
    assert.match(folderJs, /sampleRoot:\s*'body'/);
    assert.match(folderJs, /windowNameSeed=/);
    assert.match(folderJs, /storageSeedSummary=/);
    assert.match(folderJs, /windowNameSeedSummary=/);
    assert.match(folderJs, /cookieSeed=/);
    assert.match(folderJs, /navigationPrefillId=/);
    assert.match(folderJs, /foldersLoaded=/);
    assert.match(folderJs, /membersLoaded=/);
    assert.match(folderJs, /resolvedBy=/);
    assert.match(folderJs, /return safeType && safeId \? \{ type: safeType, id: safeId, folder \} : null;/);
    assert.match(folderJs, /folder:\s*payload\?\.folder && typeof payload\.folder === 'object'/);
    assert.match(folderJs, /window\.FolderViewPlusFolderEditorRuntimeLoaded = true;/);
    assert.match(folderJs, /window\.FolderViewPlusFolderEditorRuntimeBootStage = 'script-evaluated';/);
    assert.match(folderJs, /window\.FolderViewPlusFolderEditorRuntimeBootStage = 'runtime-ready';/);
    assert.match(folderJs, /const requestedFolderRefs = buildFolderEditorRefCandidates\(/);
    assert.match(folderJs, /for \(const candidateRef of requestedFolderRefs\) \{/);
    assert.match(folderJs, /currentEditFolderId = String\(\s*resolvedEditFolder\?\.id[\s\S]*\|\| bootstrapFolderId/);
    assert.match(folderPage, /\$_COOKIE\['fv_folder_editor_bootstrap'\]/);
    assert.match(folderPage, /\$folderEditorPageMode = 'modern';/);
    assert.match(folderPage, /\$folderEditorPageModeSource = 'modern-only';/);
    assert.match(folderPage, /const runtimeMode = 'modern';/);
    assert.match(folderPage, /const scriptQueue = \[[\s\S]*folder\.editor\.hierarchy\.js[\s\S]*folder\.editor\.chrome\.js[\s\S]*folder\.editor\.parent-picker\.js[\s\S]*folder\.editor\.rules\.js[\s\S]*folder\.js/);
    assert.doesNotMatch(folderPage, /folder\.legacy\.js/);
    assert.match(folderPage, /win\.FolderViewPlusCopyFolderEditorBootstrapDiagnostics = async function copyFolderEditorBootstrapDiagnostics\(\)/);
    assert.match(folderPage, /const EDITOR_DEBUG_SURFACE_STORAGE_KEY = 'fv\.folder\.editor\.debug\.surface\.v1';/);
    assert.match(folderPage, /const buildDiagnosticsSnapshot = \(\) => \(\{/);
    assert.match(folderPage, /win\.FolderViewPlusCollectFolderEditorBootstrapDiagnostics = function collectFolderEditorBootstrapDiagnostics\(\)/);
    assert.match(folderPage, /win\.localStorage\.setItem\(EDITOR_DEBUG_SURFACE_STORAGE_KEY,\s*JSON\.stringify\(buildDiagnosticsSnapshot\(\)\)\);/);
    assert.match(folderPage, /win\.FolderViewPlusReportFolderEditorBootstrap = function reportFolderEditorBootstrap\(\{/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapBanner"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapSummary"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapDetailsText"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapDebug"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapCopy"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapDisclosure"/);
    assert.match(folderPage, /syncSurfaceState\(\);/);
    assert.match(folderEditorChromeJs, /root\.FolderViewPlusReportFolderEditorBootstrap =/);
    assert.match(folderEditorChromeJs, /const pageReportFolderEditorBootstrap = typeof root\.FolderViewPlusReportFolderEditorBootstrap === 'function'/);
    assert.match(folderEditorChromeJs, /pageReportFolderEditorBootstrap\(\{\s*summary,\s*details,\s*debug,\s*tone,\s*stage: String\(root\.FolderViewPlusFolderEditorRuntimeBootStage \|\| ''\)\s*\}\);/);
    assert.match(folderEditorChromeJs, /Folder editor runtime stalled during bootstrap\./);
    assert.match(folderEditorChromeJs, /<details id="fvEditorBootstrapDetails" class="fv-editor-bootstrap-disclosure">/);
    assert.match(folderEditorChromeJs, /<summary id="fvEditorBootstrapSummary" class="fv-editor-bootstrap-summary">Bootstrap diagnostics<\/summary>/);
    assert.match(folderEditorChromeJs, /root\.addEventListener\('error'/);
    assert.match(folderEditorChromeJs, /root\.addEventListener\('unhandledrejection'/);
});

test('folder editor URLs duplicate folder identity into the hash for navigation-safe fallback', () => {
    assert.match(dockerJs, /const EDITOR_WINDOW_NAME_PREFIX = 'fv\.folder\.editor\.v1:'/);
    assert.match(dockerJs, /const EDITOR_BOOTSTRAP_COOKIE_NAME = 'fv_folder_editor_bootstrap';/);
    assert.match(dockerJs, /const EDITOR_DEBUG_LAUNCH_STORAGE_KEY = 'fv\.folder\.editor\.debug\.launch\.v1';/);
    assert.match(dockerJs, /const recordFolderEditorLaunchDebug = \(sourcePage, folderType, id, targetUrl\) =>/);
    assert.match(dockerJs, /window\.name = `\$\{EDITOR_WINDOW_NAME_PREFIX\}\$\{payload\}`;/);
    assert.match(vmJs, /const EDITOR_WINDOW_NAME_PREFIX = 'fv\.folder\.editor\.v1:'/);
    assert.match(vmJs, /const EDITOR_BOOTSTRAP_COOKIE_NAME = 'fv_folder_editor_bootstrap';/);
    assert.match(vmJs, /const EDITOR_DEBUG_LAUNCH_STORAGE_KEY = 'fv\.folder\.editor\.debug\.launch\.v1';/);
    assert.match(vmJs, /const recordFolderEditorLaunchDebug = \(sourcePage, folderType, id, targetUrl\) =>/);
    assert.match(vmJs, /window\.name = `\$\{EDITOR_WINDOW_NAME_PREFIX\}\$\{payload\}`;/);
    assert.doesNotMatch(dashboardJs, /const EDITOR_WINDOW_NAME_PREFIX = 'fv\.folder\.editor\.v1:'/);
    assert.doesNotMatch(dashboardJs, /const EDITOR_BOOTSTRAP_COOKIE_NAME = 'fv_folder_editor_bootstrap';/);
    assert.doesNotMatch(dashboardJs, /const EDITOR_DEBUG_LAUNCH_STORAGE_KEY = 'fv\.folder\.editor\.debug\.launch\.v1';/);
    assert.doesNotMatch(dashboardJs, /window\.name = `\$\{EDITOR_WINDOW_NAME_PREFIX\}\$\{payload\}`;/);
    assert.match(dockerJs, /return `\/Docker\/Folder\?\$\{params\.toString\(\)\}#\$\{hashParams\.toString\(\)\}`;/);
    assert.match(vmJs, /return `\/VMs\/Folder\?\$\{params\.toString\(\)\}#\$\{hashParams\.toString\(\)\}`;/);
    assert.doesNotMatch(dashboardJs, /return `\$\{location\.pathname\}\/Folder\?\$\{params\.toString\(\)\}#\$\{hashParams\.toString\(\)\}`;/);
});
