import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(process.cwd());
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const folderContractJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
const folderEditorSharedJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.shared.js');
const folderEditorSchemaJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.schema.js');
const folderEditorPreviewJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.preview.js');
const folderEditorPreviewRuntimeJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.preview-runtime.js');
const folderEditorStateJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.state.js');
const folderEditorMembersJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.members.js');
const folderEditorIconsJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.icons.js');
const folderEditorTypeDockerJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.type-docker.js');
const folderEditorTypeVmJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.type-vm.js');
const folderSettingsTransferJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.settings-transfer.js');
const bulkAssignmentSharedJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folderviewplus.bulk-assignment.shared.js');
const dockerPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/folderview.plus.Docker.page');
const vmPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/folderview.plus.VMs.page');
const folderPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/Folder.page');
const runtimeSharedCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/runtime.shared.css');

test('shared folder contract exports the canonical row, dropdown, and preview normalization helpers', () => {
    assert.match(folderContractJs, /^\/\/ @ts-check/m);
    assert.match(folderContractJs, /const DEFAULT_PREVIEW_BORDER_COLOR = '#afa89e';/);
    assert.match(folderContractJs, /const DEFAULT_PREVIEW_BORDER_WIDTH = 1;/);
    assert.match(folderContractJs, /const DEFAULT_PREVIEW_VERTICAL_BARS_WIDTH = 1;/);
    assert.match(folderContractJs, /const DEFAULT_DROPDOWN_STYLE = 'minimal';/);
    assert.match(folderContractJs, /const DEFAULT_DROPDOWN_COLOR = '#ff9a3c';/);
    assert.match(folderContractJs, /const DEFAULT_DROPDOWN_HOVER_COLOR = '#111111';/);
    assert.match(folderContractJs, /const SUPPORTED_DROPDOWN_STYLES = Object\.freeze\(\['minimal', 'boxed', 'ghost', 'pill', 'filled'\]\);/);
    assert.match(folderContractJs, /const normalizeHexColor = \(value,\s*fallback\) =>/);
    assert.match(folderContractJs, /const normalizePositiveInt = \(value,\s*fallback,\s*min = 1,\s*max = 4\) =>/);
    assert.match(folderContractJs, /const extractDropdownStyleValue = \(value,\s*fallbackSource = null\) =>/);
    assert.match(folderContractJs, /const normalizeDropdownStyle = \(value,\s*fallbackSource = null\) =>/);
    assert.match(folderContractJs, /const hexColorToRgba = \(hex,\s*alpha\) =>/);
    assert.match(folderContractJs, /const getDropdownStyleTokens = \(style,\s*normalColor,\s*hoverColor\) =>/);
    assert.match(folderContractJs, /const isPreviewBorderEnabled = \(settings\) =>/);
    assert.match(folderContractJs, /const extractPreviewRowLimitValue = \(value,\s*fallbackSource = null\) =>/);
    assert.match(folderContractJs, /const normalizePreviewRowLimit = \(value,\s*fallbackSource = null\) =>/);
    assert.match(folderContractJs, /window\.FolderViewPlusFolderContract = \{/);
});

test('shared folder editor module owns normalization and reset helper primitives', () => {
    assert.match(folderEditorSharedJs, /^\/\/ @ts-check/m);
    assert.match(folderEditorSharedJs, /\(function fvplusFolderEditorSharedScope\(window\) \{/);
    assert.match(folderEditorSharedJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(folderEditorSharedJs, /const normalizeOptionalHealthSelect = \(value,\s*allowedValues\) =>/);
    assert.match(folderEditorSharedJs, /const parseOptionalThresholdInput = \(value\) =>/);
    assert.match(folderEditorSharedJs, /const extractPreviewRowLimitValue = typeof deps\.extractPreviewRowLimitValue === 'function'/);
    assert.match(folderEditorSharedJs, /const normalizePreviewRowLimit = typeof deps\.normalizePreviewRowLimit === 'function'/);
    assert.match(folderEditorSharedJs, /const normalizeFolderRecordForEditor = \(folder\) =>/);
    assert.match(folderEditorSharedJs, /const createResetHelpers = \(deps = \{\}\) =>/);
    assert.match(folderEditorSharedJs, /const resetPreviewBorderDefaults = \(\) =>/);
    assert.match(folderEditorSharedJs, /const resetDropdownColorDefaults = \(\) =>/);
    assert.match(folderEditorSharedJs, /window\.FolderViewPlusFolderEditorShared = Object\.freeze\(\{/);
});

test('shared folder editor schema and preview modules publish the editor-facing contracts', () => {
    assert.match(folderEditorSchemaJs, /^\/\/ @ts-check/m);
    assert.match(folderEditorSchemaJs, /\(function fvplusFolderEditorSchemaScope\(window\) \{/);
    assert.match(folderEditorSchemaJs, /const createModernSchema = \(deps = \{\}\) =>/);
    assert.match(folderEditorSchemaJs, /window\.FolderViewPlusFolderEditorSchema = Object\.freeze\(\{/);
    assert.match(folderEditorSchemaJs, /window\.FolderViewPlusFolderEditorSchemaModuleLoaded = true/);
    assert.match(folderEditorPreviewJs, /^\/\/ @ts-check/m);
    assert.match(folderEditorPreviewJs, /\(function fvplusFolderEditorPreviewScope\(window\) \{/);
    assert.match(folderEditorPreviewJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(folderEditorPreviewJs, /const renderLivePreviewCanvas = \(\) =>/);
    assert.match(folderEditorPreviewJs, /const updateLiveSummary = \(\) =>/);
    assert.match(folderEditorPreviewJs, /window\.FolderViewPlusFolderEditorPreview = Object\.freeze\(\{/);
    assert.match(folderEditorPreviewJs, /window\.FolderViewPlusFolderEditorPreviewModuleLoaded = true/);
    assert.match(folderEditorPreviewRuntimeJs, /^\/\/ @ts-check/m);
    assert.match(folderEditorPreviewRuntimeJs, /root\.FolderViewPlusFolderEditorPreviewRuntime = factory\(\);/);
    assert.match(folderEditorPreviewRuntimeJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(folderEditorPreviewRuntimeJs, /const schedulePreviewRender = \(\) =>/);
    assert.match(folderEditorPreviewRuntimeJs, /const updatePreviewConstraints = \(\) =>/);
    assert.match(folderEditorPreviewRuntimeJs, /root\.FolderViewPlusFolderEditorPreviewRuntimeModuleLoaded = true/);
    assert.match(folderEditorStateJs, /^\/\/ @ts-check/m);
    assert.match(folderEditorStateJs, /root\.FolderViewPlusFolderEditorState = factory\(\);/);
    assert.match(folderEditorStateJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(folderEditorStateJs, /const updateUnsavedIndicator = \(\) =>/);
    assert.match(folderEditorStateJs, /const buildEditorActionBar = \(\) =>/);
    assert.match(folderEditorStateJs, /root\.FolderViewPlusFolderEditorStateModuleLoaded = true/);
    assert.match(folderEditorMembersJs, /^\/\/ @ts-check/m);
    assert.match(folderEditorMembersJs, /root\.FolderViewPlusFolderEditorMembers = factory\(\);/);
    assert.match(folderEditorMembersJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(folderEditorMembersJs, /const applyMemberFilters = \(\) =>/);
    assert.match(folderEditorMembersJs, /const moveMemberRow = \(button,\s*direction\) =>/);
    assert.match(folderEditorMembersJs, /root\.FolderViewPlusFolderEditorMembersModuleLoaded = true/);
    assert.match(folderEditorIconsJs, /^\/\/ @ts-check/m);
    assert.match(folderEditorIconsJs, /root\.FolderViewPlusFolderEditorIcons = factory\(\);/);
    assert.match(folderEditorIconsJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(folderEditorIconsJs, /const bindIconPickerEvents = async \(\) =>/);
    assert.match(folderEditorIconsJs, /const renderBuiltInIconPicker = \(\) =>/);
    assert.match(folderEditorIconsJs, /root\.FolderViewPlusFolderEditorIconsModuleLoaded = true/);
    assert.match(folderEditorTypeDockerJs, /^\/\/ @ts-check/m);
    assert.match(folderEditorTypeDockerJs, /root\.FolderViewPlusFolderEditorTypeDocker = factory\(\);/);
    assert.match(folderEditorTypeDockerJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(folderEditorTypeDockerJs, /const shouldSyncAfterSave = \(nextFolder,\s*options = \{\}\) =>/);
    assert.match(folderEditorTypeDockerJs, /const flushPostSaveSync = async \(options = \{\}\) =>/);
    assert.match(folderEditorTypeDockerJs, /const mapRuntimeMember = \(entry = \{\}\) =>/);
    assert.match(folderEditorTypeDockerJs, /const collectSectionRows = \(\{ form,\s*findBasicByFieldName \} = \{\}\) =>/);
    assert.match(folderEditorTypeDockerJs, /const applySectionTags = \(\{ markSection,\s*markAdvanced \} = \{\}\) =>/);
    assert.match(folderEditorTypeDockerJs, /const getPreviewSignals = \(\{ selectedMembers = \[\] \} = \{\}\) =>/);
    assert.match(folderEditorTypeDockerJs, /const getRulesConfig = \(\) => DOCKER_RULES_CONFIG;/);
    assert.match(folderEditorTypeDockerJs, /const buildSmartDefaultSuggestions = \(\{ selectedMembers = \[\],\s*form \} = \{\}\) =>/);
    assert.match(folderEditorTypeDockerJs, /root\.FolderViewPlusFolderEditorTypeDockerModuleLoaded = true/);
    assert.match(folderEditorTypeVmJs, /^\/\/ @ts-check/m);
    assert.match(folderEditorTypeVmJs, /root\.FolderViewPlusFolderEditorTypeVm = factory\(\);/);
    assert.match(folderEditorTypeVmJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(folderEditorTypeVmJs, /const mapRuntimeMember = \(entry = \{\}\) =>/);
    assert.match(folderEditorTypeVmJs, /const getRulesConfig = \(\) => VM_RULES_CONFIG;/);
    assert.match(folderEditorTypeVmJs, /applyPreviewConstraints:/);
    assert.match(folderEditorTypeVmJs, /root\.FolderViewPlusFolderEditorTypeVmModuleLoaded = true/);
    assert.match(folderSettingsTransferJs, /^\/\/ @ts-check/m);
    assert.match(folderSettingsTransferJs, /root\.FolderViewPlusFolderSettingsTransfer = factory\(\);/);
    assert.match(folderSettingsTransferJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(folderSettingsTransferJs, /const normalizeFolderSettingsPayload = \(payload\) =>/);
    assert.match(folderSettingsTransferJs, /const buildClipboardEntry = \(type,\s*folder,\s*options = \{\}\) =>/);
    assert.match(folderSettingsTransferJs, /root\.FolderViewPlusFolderSettingsTransferModuleLoaded = true/);
    assert.match(bulkAssignmentSharedJs, /^\/\/ @ts-check/m);
    assert.match(bulkAssignmentSharedJs, /root\.FolderViewPlusBulkAssignmentShared = factory\(\);/);
    assert.match(bulkAssignmentSharedJs, /const createApi = \(deps = \{\}\) =>/);
    assert.match(bulkAssignmentSharedJs, /const buildBulkAssignmentPlan = \(type,\s*folderId,\s*namesInput = null\) =>/);
    assert.match(bulkAssignmentSharedJs, /const executeBulkAssignmentPlan = async \(type,\s*planInput,\s*options = \{\}\) =>/);
    assert.match(bulkAssignmentSharedJs, /root\.FolderViewPlusBulkAssignmentSharedModuleLoaded = true/);
});

test('runtime pages and folder editor load the shared contract before their consumers', () => {
    const dockerThemeResolverIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.theme-resolver.js');
    const dockerContractIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
    const dockerSettingsTransferIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/folder.settings-transfer.js');
    const dockerSharedRuntimeIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.shared.js');
    const dockerRuntimeIndex = dockerPage.indexOf('/plugins/folderview.plus/scripts/docker.js');
    const dockerThemeTokensCssIndex = dockerPage.indexOf('/plugins/folderview.plus/styles/theme.tokens.css');
    const dockerSharedCssIndex = dockerPage.indexOf('/plugins/folderview.plus/styles/runtime.shared.css');
    const dockerTypeCssIndex = dockerPage.indexOf('/plugins/folderview.plus/styles/docker.css');
    const vmThemeResolverIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.theme-resolver.js');
    const vmContractIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
    const vmSettingsTransferIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/folder.settings-transfer.js');
    const vmSharedRuntimeIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.shared.js');
    const vmRuntimeIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/vm.js');
    const vmThemeTokensCssIndex = vmPage.indexOf('/plugins/folderview.plus/styles/theme.tokens.css');
    const vmSharedCssIndex = vmPage.indexOf('/plugins/folderview.plus/styles/runtime.shared.css');
    const vmTypeCssIndex = vmPage.indexOf('/plugins/folderview.plus/styles/vm.css');
    const folderThemeResolverIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.theme-resolver.js');
    const folderContractIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
    const folderSharedEditorIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.shared.js');
    const folderSchemaIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.schema.js');
    const folderPreviewIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.preview.js');
    const folderPreviewRuntimeIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.preview-runtime.js');
    const folderHierarchyIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.hierarchy.js');
    const folderParentPickerIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.parent-picker.js');
    const folderSettingsTransferIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.settings-transfer.js');
    const folderBulkAssignmentSharedIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.bulk-assignment.shared.js');
    const folderStateIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.state.js');
    const folderMembersIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.members.js');
    const folderIconsIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.icons.js');
    const folderTypeDockerIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.type-docker.js');
    const folderTypeVmIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.type-vm.js');
    const folderModernIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.js');
    const folderChromeIndex = folderPage.indexOf('/plugins/folderview.plus/scripts/folder.editor.chrome.js');
    const folderBootLoaderIndex = folderPage.indexOf('const scriptQueue = [');

    assert.ok(dockerThemeResolverIndex >= 0, 'docker page missing shared theme resolver include');
    assert.ok(dockerContractIndex >= 0, 'docker page missing shared folder contract include');
    assert.ok(dockerSettingsTransferIndex >= 0, 'docker page missing folder settings transfer include');
    assert.ok(dockerSharedRuntimeIndex >= 0, 'docker page missing shared runtime include');
    assert.ok(dockerRuntimeIndex >= 0, 'docker page missing docker runtime include');
    assert.ok(dockerThemeResolverIndex < dockerSharedRuntimeIndex, 'theme resolver must load before docker.runtime.shared.js');
    assert.ok(dockerThemeResolverIndex < dockerRuntimeIndex, 'theme resolver must load before docker.js');
    assert.ok(dockerContractIndex < dockerSharedRuntimeIndex, 'shared contract must load before docker.runtime.shared.js');
    assert.ok(dockerContractIndex < dockerSettingsTransferIndex, 'shared contract must load before folder.settings-transfer.js on docker page');
    assert.ok(dockerSettingsTransferIndex < dockerRuntimeIndex, 'folder.settings-transfer.js must load before docker.js');
    assert.ok(dockerContractIndex < dockerRuntimeIndex, 'shared contract must load before docker.js');
    assert.ok(dockerThemeTokensCssIndex >= 0, 'docker page missing shared theme token stylesheet');
    assert.ok(dockerSharedCssIndex >= 0, 'docker page missing shared runtime stylesheet');
    assert.ok(dockerTypeCssIndex >= 0, 'docker page missing docker stylesheet');
    assert.ok(dockerThemeTokensCssIndex < dockerSharedCssIndex, 'theme token stylesheet must load before shared runtime stylesheet on docker page');
    assert.ok(dockerSharedCssIndex < dockerTypeCssIndex, 'shared runtime stylesheet must load before docker.css');

    assert.ok(vmThemeResolverIndex >= 0, 'vm page missing shared theme resolver include');
    assert.ok(vmContractIndex >= 0, 'vm page missing shared folder contract include');
    assert.ok(vmSettingsTransferIndex >= 0, 'vm page missing folder settings transfer include');
    assert.ok(vmSharedRuntimeIndex >= 0, 'vm page missing shared runtime include');
    assert.ok(vmRuntimeIndex >= 0, 'vm page missing vm runtime include');
    assert.ok(vmThemeResolverIndex < vmSharedRuntimeIndex, 'theme resolver must load before shared runtime on VMs page');
    assert.ok(vmThemeResolverIndex < vmRuntimeIndex, 'theme resolver must load before vm.js');
    assert.ok(vmContractIndex < vmSharedRuntimeIndex, 'shared contract must load before shared runtime on VMs page');
    assert.ok(vmContractIndex < vmSettingsTransferIndex, 'shared contract must load before folder.settings-transfer.js on VMs page');
    assert.ok(vmSettingsTransferIndex < vmRuntimeIndex, 'folder.settings-transfer.js must load before vm.js');
    assert.ok(vmContractIndex < vmRuntimeIndex, 'shared contract must load before vm.js');
    assert.ok(vmThemeTokensCssIndex >= 0, 'vm page missing shared theme token stylesheet');
    assert.ok(vmSharedCssIndex >= 0, 'vm page missing shared runtime stylesheet');
    assert.ok(vmTypeCssIndex >= 0, 'vm page missing vm stylesheet');
    assert.ok(vmThemeTokensCssIndex < vmSharedCssIndex, 'theme token stylesheet must load before shared runtime stylesheet on VMs page');
    assert.ok(vmSharedCssIndex < vmTypeCssIndex, 'shared runtime stylesheet must load before vm.css');

    assert.ok(folderThemeResolverIndex >= 0, 'folder editor page missing shared theme resolver include');
    assert.ok(folderContractIndex >= 0, 'folder editor page missing shared folder contract include');
    assert.ok(folderSharedEditorIndex >= 0, 'folder editor page missing shared editor include');
    assert.ok(folderSchemaIndex >= 0, 'folder editor page missing shared schema include');
    assert.ok(folderPreviewIndex >= 0, 'folder editor page missing shared preview include');
    assert.ok(folderPreviewRuntimeIndex >= 0, 'folder editor page missing preview runtime include');
    assert.ok(folderBootLoaderIndex >= 0, 'folder editor page missing runtime boot loader');
    assert.ok(folderHierarchyIndex >= 0, 'folder editor page missing hierarchy module include');
    assert.ok(folderParentPickerIndex >= 0, 'folder editor page missing parent picker module include');
    assert.ok(folderSettingsTransferIndex >= 0, 'folder editor page missing folder settings transfer module include');
    assert.ok(folderBulkAssignmentSharedIndex >= 0, 'folder editor page missing shared bulk assignment module include');
    assert.ok(folderStateIndex >= 0, 'folder editor page missing state module include');
    assert.ok(folderMembersIndex >= 0, 'folder editor page missing members module include');
    assert.ok(folderIconsIndex >= 0, 'folder editor page missing icons module include');
    assert.ok(folderTypeDockerIndex >= 0, 'folder editor page missing docker type module include');
    assert.ok(folderTypeVmIndex >= 0, 'folder editor page missing VM type module include');
    assert.ok(folderModernIndex >= 0, 'folder editor page missing modern runtime include');
    assert.ok(folderChromeIndex >= 0, 'folder editor page missing chrome runtime include');
    assert.ok(folderThemeResolverIndex < folderSharedEditorIndex, 'theme resolver must load before folder.editor.shared.js');
    assert.ok(folderContractIndex < folderSharedEditorIndex, 'shared contract must load before folder.editor.shared.js');
    assert.ok(folderSharedEditorIndex < folderSchemaIndex, 'shared editor module must load before folder.editor.schema.js');
    assert.ok(folderSchemaIndex < folderPreviewIndex, 'shared schema must load before folder.editor.preview.js');
    assert.ok(folderPreviewIndex < folderPreviewRuntimeIndex, 'preview renderer must load before folder.editor.preview-runtime.js');
    assert.ok(folderHierarchyIndex < folderParentPickerIndex, 'hierarchy module must load before folder.editor.parent-picker.js');
    assert.ok(folderParentPickerIndex < folderSettingsTransferIndex, 'parent picker module must load before folder.settings-transfer.js');
    assert.ok(folderSettingsTransferIndex < folderBulkAssignmentSharedIndex, 'folder.settings-transfer.js must load before folderviewplus.bulk-assignment.shared.js');
    assert.ok(folderBulkAssignmentSharedIndex < folderStateIndex, 'folderviewplus.bulk-assignment.shared.js must load before folder.editor.state.js');
    assert.ok(folderStateIndex < folderMembersIndex, 'state module must load before folder.editor.members.js');
    assert.ok(folderMembersIndex < folderIconsIndex, 'members module must load before folder.editor.icons.js');
    assert.ok(folderIconsIndex < folderTypeDockerIndex, 'icons module must load before folder.editor.type-docker.js');
    assert.ok(folderTypeDockerIndex < folderTypeVmIndex, 'docker type module must load before folder.editor.type-vm.js');
    assert.ok(folderTypeVmIndex < folderModernIndex, 'VM type module must load before folder.js');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/icon-picker.runtime.js'"), 'folder editor page missing boot-loaded icon picker runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.editor.hierarchy.js'"), 'folder editor page missing boot-loaded hierarchy runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.editor.parent-picker.js'"), 'folder editor page missing boot-loaded parent picker runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.settings-transfer.js'"), 'folder editor page missing boot-loaded folder settings transfer runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folderviewplus.bulk-assignment.shared.js'"), 'folder editor page missing boot-loaded shared bulk assignment runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.editor.chrome.js'"), 'folder editor page missing boot-loaded chrome runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.editor.state.js'"), 'folder editor page missing boot-loaded state runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.editor.members.js'"), 'folder editor page missing boot-loaded members runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.editor.icons.js'"), 'folder editor page missing boot-loaded icons runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.editor.type-docker.js'"), 'folder editor page missing boot-loaded docker type runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.editor.type-vm.js'"), 'folder editor page missing boot-loaded VM type runtime');
    assert.ok(folderPage.includes("'/plugins/folderview.plus/scripts/folder.js'"), 'folder editor page missing boot-loaded modern runtime');
    assert.ok(!folderPage.includes("'/plugins/folderview.plus/scripts/folder.legacy.js'"), 'folder editor page should not boot-load the retired legacy runtime');
});

test('shared runtime stylesheet owns the common dropdown and preview geometry contract', () => {
    assert.match(runtimeSharedCss, /\.folder-dropdown\s*\{[\s\S]*margin:\s*0 var\(--fvplus-folder-dropdown-right-margin,\s*16px\) 0 auto/);
    assert.match(runtimeSharedCss, /\.folder-dropdown > i\s*\{[\s\S]*font-size:\s*var\(--fvplus-folder-dropdown-icon-size,\s*12px\) !important/);
    assert.match(runtimeSharedCss, /\.folder-dropdown:hover,\s*[\s\S]*visibility:\s*visible !important/);
    assert.match(runtimeSharedCss, /\.folder-dropdown:hover > i,\s*[\s\S]*opacity:\s*1 !important/);
    assert.match(runtimeSharedCss, /\.folder-preview\s*\{[\s\S]*align-items:\s*center;[\s\S]*align-content:\s*flex-start;/);
    assert.match(runtimeSharedCss, /\.folder-preview-wrapper\s*\{[\s\S]*margin-top:\s*var\(--fvplus-preview-wrapper-margin-top,\s*6px\)/);
    assert.match(runtimeSharedCss, /\.folder-preview-wrapper > span\.outer\s*\{[\s\S]*display:\s*inline-flex;[\s\S]*align-items:\s*center;/);
});
