import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const folderJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.js');
const folderLegacyJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.legacy.js');
const dockerJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/docker.js');
const vmJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/vm.js');
const dashboardJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/dashboard.js');
const folderPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/Folder.page');
const folderEditorChromeJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/folder.editor.chrome.js');

test('folder editor runtimes accept query and hash bootstrap identity fallbacks', () => {
    assert.match(folderJs, /const readFolderEditorBootstrapSeed = \(\) =>/);
    assert.match(folderJs, /const readWindowNameFolderEditorBootstrapSeed = \(\) =>/);
    assert.match(folderJs, /const readCookieFolderEditorBootstrapSeed = \(\) =>/);
    assert.match(folderJs, /const EDITOR_DEBUG_BOOTSTRAP_STORAGE_KEY = 'fv\.folder\.editor\.debug\.bootstrap\.v1';/);
    assert.match(folderJs, /const recordFolderEditorBootstrapDebug = \(details = \{\}\) =>/);
    assert.match(folderJs, /const buildFolderEditorRefCandidates = \(\.\.\.values\) => Array\.from\(new Set/);
    assert.match(folderJs, /folderEditorBootstrapSeed\?\.type/);
    assert.match(folderJs, /folderEditorBootstrapSeed\?\.id/);
    assert.match(folderJs, /folderEditorBootstrapSeed\?\.folder/);
    assert.match(folderJs, /const folderEditorCookieBootstrap = readCookieFolderEditorBootstrapSeed\(\);/);
    assert.match(folderJs, /const folderEditorBootstrapSeed = folderEditorWindowNameBootstrap \|\| folderEditorStorageBootstrap \|\| folderEditorCookieBootstrap;/);
    assert.match(folderJs, /routeTargetRecovered: details\.routeTargetRecovered === true,/);
    assert.match(folderJs, /routeTargetMismatch: details\.routeTargetMismatch === true/);
    assert.match(folderJs, /const folderEditorHashParams = new URLSearchParams/);
    assert.match(folderJs, /const normalizedExpectedType = String\(expectedType \|\| ''\)\.trim\(\);/);
    assert.match(folderJs, /if \(normalizedExpectedType && normalizedType !== normalizedExpectedType\) \{/);
    assert.match(folderJs, /folderEditorHashParams\.get\('type'\)/);
    assert.match(folderJs, /folderEditorHashParams\.get\('id'\)/);
    assert.match(folderJs, /folderThemeSurfaceBinding\?\.runApply\('chrome-ready'\)/);
    assert.match(folderJs, /sampleRoot:\s*'body'/);
    assert.match(folderJs, /windowNameSeed=/);
    assert.match(folderJs, /storageSeedSummary=/);
    assert.match(folderJs, /windowNameSeedSummary=/);
    assert.match(folderJs, /cookieSeed=/);
    assert.match(folderJs, /navigationPrefillId=/);
    assert.match(folderJs, /foldersLoaded=/);
    assert.match(folderJs, /membersLoaded=/);
    assert.match(folderJs, /resolvedBy=/);
    assert.match(folderJs, /return safeType && safeId \? \{ type: safeType, id: safeId, folder \} : null;/);
    assert.match(folderJs, /folder:\s*payload\?\.folder && typeof payload\.folder === 'object'/);
    assert.match(folderJs, /window\.FolderViewPlusFolderEditorRuntimeLoaded = true;/);
    assert.match(folderJs, /window\.FolderViewPlusFolderEditorRuntimeBootStage = 'script-evaluated';/);
    assert.match(folderJs, /window\.FolderViewPlusFolderEditorRuntimeBootStage = 'runtime-ready';/);
    assert.match(folderJs, /const requestedFolderRefs = buildFolderEditorRefCandidates\(/);
    assert.match(folderJs, /for \(const candidateRef of requestedFolderRefs\) \{/);
    assert.match(folderJs, /currentEditFolderId = String\(\s*resolvedEditFolder\?\.id[\s\S]*\|\| bootstrapFolderId/);
    assert.match(folderPage, /\$_COOKIE\['fv_folder_editor_bootstrap'\]/);
    assert.match(folderPage, /\$folderEditorCookieType = trim/);
    assert.match(folderPage, /\$folderEditorCookieId = trim/);
    assert.match(folderPage, /win\.FolderViewPlusCopyFolderEditorBootstrapDiagnostics = async function copyFolderEditorBootstrapDiagnostics\(\)/);
    assert.match(folderPage, /win\.FolderViewPlusReportFolderEditorBootstrap = function reportFolderEditorBootstrap\(\{/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapBanner"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapSummary"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapDetailsText"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapDebug"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapCopy"/);
    assert.match(folderPage, /id="fvFolderEditorBootstrapDisclosure"/);
    assert.match(folderLegacyJs, /const readFolderEditorBootstrapSeed = \(\) =>/);
    assert.match(folderLegacyJs, /const readWindowNameFolderEditorBootstrapSeed = \(\) =>/);
    assert.match(folderLegacyJs, /const readCookieFolderEditorBootstrapSeed = \(\) =>/);
    assert.match(folderLegacyJs, /const EDITOR_DEBUG_LAUNCH_STORAGE_KEY = 'fv\.folder\.editor\.debug\.launch\.v1';/);
    assert.match(folderLegacyJs, /const EDITOR_DEBUG_BOOTSTRAP_STORAGE_KEY = 'fv\.folder\.editor\.debug\.bootstrap\.v1';/);
    assert.match(folderLegacyJs, /const recordFolderEditorBootstrapDebug = \(details = \{\}\) =>/);
    assert.match(folderLegacyJs, /const setLegacyEditorBootstrapDiagnostics = \(details = \{\}\) =>/);
    assert.match(folderLegacyJs, /const copyLegacyEditorBootstrapDiagnostics = async \(\) =>/);
    assert.match(folderLegacyJs, /const buildFolderEditorRefCandidates = \(\.\.\.values\) => Array\.from\(new Set/);
    assert.match(folderLegacyJs, /folderEditorBootstrapSeed\?\.type/);
    assert.match(folderLegacyJs, /folderEditorBootstrapSeed\?\.id/);
    assert.match(folderLegacyJs, /folderEditorBootstrapSeed\?\.folder/);
    assert.match(folderLegacyJs, /window\.FolderViewPlusFolderEditorRuntimeLoaded = true;/);
    assert.match(folderLegacyJs, /window\.FolderViewPlusFolderEditorRuntimeBootStage = 'script-evaluated';/);
    assert.match(folderLegacyJs, /window\.FolderViewPlusReportFolderEditorBootstrap = \(\{/);
    assert.match(folderLegacyJs, /window\.addEventListener\('error', \(event\) => \{/);
    assert.match(folderLegacyJs, /window\.addEventListener\('unhandledrejection', \(event\) => \{/);
    assert.match(folderLegacyJs, /const pageReportFolderEditorBootstrap = typeof window\.FolderViewPlusReportFolderEditorBootstrap === 'function'/);
    assert.match(folderLegacyJs, /folderEditorWindowNameBootstrap/);
    assert.match(folderLegacyJs, /const folderEditorCookieBootstrap = readCookieFolderEditorBootstrapSeed\(\);/);
    assert.match(folderLegacyJs, /folderEditorBootstrapSeed = folderEditorWindowNameBootstrap \|\| folderEditorStorageBootstrap \|\| folderEditorCookieBootstrap/);
    assert.match(folderLegacyJs, /return safeType && safeId \? \{ type: safeType, id: safeId, folder \} : null;/);
    assert.match(folderLegacyJs, /folder:\s*payload\?\.folder && typeof payload\.folder === 'object'/);
    assert.match(folderLegacyJs, /const folderEditorHashParams = new URLSearchParams/);
    assert.match(folderLegacyJs, /const normalizedExpectedType = String\(expectedType \|\| ''\)\.trim\(\);/);
    assert.match(folderLegacyJs, /if \(normalizedExpectedType && normalizedType !== normalizedExpectedType\) \{/);
    assert.match(folderLegacyJs, /folderEditorHashParams\.get\('type'\)/);
    assert.match(folderLegacyJs, /folderEditorHashParams\.get\('id'\)/);
    assert.match(folderLegacyJs, /const getFormField = \(form, fieldName\) =>/);
    assert.match(folderLegacyJs, /const hydrateCurrentEditFolder = \(folderRecord, folderRecordId, foldersMap = \{\}, options = \{\}\) =>/);
    assert.match(folderLegacyJs, /const buildFolderEditorRuntimeUrl = \(folderType, id = ''\) =>/);
    assert.match(folderLegacyJs, /const maybeRefreshLegacyEditorTargetFromPrefill = \(\) =>/);
    assert.match(folderLegacyJs, /let legacyEditorPrefillMonitorLastId = '';/);
    assert.match(folderLegacyJs, /window\.addEventListener\('storage', \(event\) => \{/);
    assert.match(folderLegacyJs, /if \(String\(event\?\.key \|\| ''\) !== EDITOR_PREFILL_LOCAL_STORAGE_KEY\)/);
    assert.match(folderLegacyJs, /window\.addEventListener\('focus', \(\) => \{/);
    assert.match(folderLegacyJs, /window\.addEventListener\('pageshow', \(\) => \{/);
    assert.match(folderLegacyJs, /document\.addEventListener\('visibilitychange', \(\) => \{/);
    assert.match(folderLegacyJs, /window\.setInterval\(\(\) => \{/);
    assert.match(folderLegacyJs, /maybeRefreshLegacyEditorTargetFromPrefill\(\);\s*\}, 500\);/);
    assert.match(folderLegacyJs, /const latestPrefill = readEditorNavigationPrefill\(type,\s*''\)\s*\|\|\s*readEditorNavigationPrefill\('',\s*''\)\s*\|\|\s*folderEditorCookieBootstrap;/);
    assert.match(folderLegacyJs, /const nextType = String\(type \|\| latestPrefill\?\.type \|\| folderEditorCookieBootstrap\?\.type \|\| ''\)\.trim\(\);/);
    assert.match(folderLegacyJs, /window\.location\.replace\(nextUrl\);/);
    assert.match(folderLegacyJs, /routeTargetRecovered: !folderId && Boolean\(currentEditFolderId\),/);
    assert.match(folderLegacyJs, /routeTargetMismatch: Boolean\(folderId && currentEditFolderId && folderId !== currentEditFolderId\)/);
    assert.match(folderLegacyJs, /const requestedFolderRefs = buildFolderEditorRefCandidates\(/);
    assert.match(folderLegacyJs, /for \(const candidateRef of requestedFolderRefs\) \{/);
    assert.match(folderLegacyJs, /currentEditFolderId = String\(\s*resolvedEditFolder\?\.id[\s\S]*\|\| bootstrapFolderId/);
    assert.match(folderLegacyJs, /hydrateCurrentEditFolder\(currentEditFolder,\s*currentEditFolderId,\s*folders,\s*\{\s*clearPrefill:\s*true\s*\}\);/);
    assert.match(folderLegacyJs, /let readInfoResponse = \{\};/);
    assert.match(folderLegacyJs, /console\.error\('\[FolderView Plus\] Legacy folder editor member inventory load failed\.'/);
    assert.match(folderLegacyJs, /choose = Object\.values\(readInfoResponse && typeof readInfoResponse === 'object' \? readInfoResponse : \{\}\)\s*\.map\(typeFilter\)\s*\.filter\(Boolean\);/);
    assert.match(folderLegacyJs, /Legacy editor opened without an edit target\./);
    assert.match(folderLegacyJs, /will keep watching the shared editor prefill and auto-refresh when that target arrives\./);
    assert.match(folderLegacyJs, /<button type="button" id="fvEditorCopyBootstrapDebug" class="fv-section-tool" data-default-label="Copy diagnostics">/);
    assert.match(folderLegacyJs, /<details id="fvEditorBootstrapDetails" class="fv-editor-bootstrap-disclosure">/);
    assert.match(folderLegacyJs, /<summary id="fvEditorBootstrapSummary" class="fv-editor-bootstrap-summary">Bootstrap diagnostics<\/summary>/);
    assert.match(folderLegacyJs, /<pre id="fvEditorBootstrapDebug" class="fv-editor-bootstrap-debug">Bootstrap: waiting for legacy folder editor runtime\.<\/pre>/);
    assert.match(folderLegacyJs, /\$\('#fvEditorCopyBootstrapDebug'\)\.off\('click'\)\.on\('click', \(\) => \{/);
    assert.match(folderLegacyJs, /applyLegacyEditorBootstrapSurfaceState\(\);/);
    assert.match(folderLegacyJs, /window\.FolderViewPlusFolderEditorRuntimeBootStage = 'shell-ready';/);
    assert.match(folderLegacyJs, /window\.FolderViewPlusFolderEditorRuntimeBootStage = 'runtime-ready';/);
    assert.match(folderLegacyJs, /sampleRoot:\s*'body'/);
    assert.match(folderEditorChromeJs, /root\.FolderViewPlusReportFolderEditorBootstrap =/);
    assert.match(folderEditorChromeJs, /Folder editor runtime stalled during bootstrap\./);
    assert.match(folderEditorChromeJs, /<details id="fvEditorBootstrapDetails" class="fv-editor-bootstrap-disclosure">/);
    assert.match(folderEditorChromeJs, /<summary id="fvEditorBootstrapSummary" class="fv-editor-bootstrap-summary">Bootstrap diagnostics<\/summary>/);
    assert.match(folderEditorChromeJs, /root\.addEventListener\('error'/);
    assert.match(folderEditorChromeJs, /root\.addEventListener\('unhandledrejection'/);
});

test('folder editor URLs duplicate folder identity into the hash for navigation-safe fallback', () => {
    assert.match(dockerJs, /const EDITOR_WINDOW_NAME_PREFIX = 'fv\.folder\.editor\.v1:'/);
    assert.match(dockerJs, /const EDITOR_BOOTSTRAP_COOKIE_NAME = 'fv_folder_editor_bootstrap';/);
    assert.match(dockerJs, /const EDITOR_DEBUG_LAUNCH_STORAGE_KEY = 'fv\.folder\.editor\.debug\.launch\.v1';/);
    assert.match(dockerJs, /const recordFolderEditorLaunchDebug = \(sourcePage, folderType, id, targetUrl\) =>/);
    assert.match(dockerJs, /window\.name = `\$\{EDITOR_WINDOW_NAME_PREFIX\}\$\{payload\}`;/);
    assert.match(vmJs, /const EDITOR_WINDOW_NAME_PREFIX = 'fv\.folder\.editor\.v1:'/);
    assert.match(vmJs, /const EDITOR_BOOTSTRAP_COOKIE_NAME = 'fv_folder_editor_bootstrap';/);
    assert.match(vmJs, /const EDITOR_DEBUG_LAUNCH_STORAGE_KEY = 'fv\.folder\.editor\.debug\.launch\.v1';/);
    assert.match(vmJs, /const recordFolderEditorLaunchDebug = \(sourcePage, folderType, id, targetUrl\) =>/);
    assert.match(vmJs, /window\.name = `\$\{EDITOR_WINDOW_NAME_PREFIX\}\$\{payload\}`;/);
    assert.match(dashboardJs, /const EDITOR_WINDOW_NAME_PREFIX = 'fv\.folder\.editor\.v1:'/);
    assert.match(dashboardJs, /const EDITOR_BOOTSTRAP_COOKIE_NAME = 'fv_folder_editor_bootstrap';/);
    assert.match(dashboardJs, /const EDITOR_DEBUG_LAUNCH_STORAGE_KEY = 'fv\.folder\.editor\.debug\.launch\.v1';/);
    assert.match(dashboardJs, /window\.name = `\$\{EDITOR_WINDOW_NAME_PREFIX\}\$\{payload\}`;/);
    assert.match(dockerJs, /return `\/Docker\/Folder\?\$\{params\.toString\(\)\}#\$\{hashParams\.toString\(\)\}`;/);
    assert.match(vmJs, /return `\/VMs\/Folder\?\$\{params\.toString\(\)\}#\$\{hashParams\.toString\(\)\}`;/);
    assert.match(dashboardJs, /return `\$\{location\.pathname\}\/Folder\?\$\{params\.toString\(\)\}#\$\{hashParams\.toString\(\)\}`;/);
});

test('legacy editor hydrates existing folder state before member inventory loads', () => {
    const hydrateIndex = folderLegacyJs.indexOf("hydrateCurrentEditFolder(currentEditFolder, currentEditFolderId, folders, { clearPrefill: true });");
    const readInfoIndex = folderLegacyJs.indexOf('let readInfoResponse = {};');
    assert.ok(hydrateIndex !== -1 && readInfoIndex > hydrateIndex, 'legacy editor must hydrate the edit form before requesting member inventory');
});
