import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = path.resolve(process.cwd());
const read = (relativePath) => fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');

const vmPage = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/folderview.plus.VMs.page');
const vmJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/vm.js');
const runtimeHostAdapterJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/runtime.host-adapter.js');
const vmLifecycleJs = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/scripts/vm.runtime.lifecycle.js');
const vmCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/vm.css');
const runtimeSharedCss = read('src/folderview.plus/usr/local/emhttp/plugins/folderview.plus/styles/runtime.shared.css');

test('vm runtime page loads shared runtime module before vm runtime script', () => {
    const fatalBannerIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.fatal-banner.js');
    const contractIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.folder-contract.js');
    const snapshotIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/folderviewplus.runtime-snapshot.js');
    const sharedIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/docker.runtime.shared.js');
    const stateObserverIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/folder.runtime.state-observers.js');
    const hostAdapterIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/runtime.host-adapter.js');
    const orderingIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/runtime.folder-ordering.js');
    const lifecycleIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/vm.runtime.lifecycle.js');
    const runtimeIndex = vmPage.indexOf('/plugins/folderview.plus/scripts/vm.js');
    const themeTokensCssIndex = vmPage.indexOf('/plugins/folderview.plus/styles/theme.tokens.css');
    const sharedCssIndex = vmPage.indexOf('/plugins/folderview.plus/styles/runtime.shared.css');
    const vmCssIndex = vmPage.indexOf('/plugins/folderview.plus/styles/vm.css');
    assert.ok(fatalBannerIndex >= 0, 'vm page should load the shared fatal banner runtime');
    assert.ok(contractIndex >= 0, 'shared folder contract include missing from VMs page');
    assert.ok(snapshotIndex >= 0, 'runtime snapshot client include missing from VMs page');
    assert.ok(sharedIndex >= 0, 'shared runtime include missing from VMs page');
    assert.ok(stateObserverIndex >= 0, 'runtime state observer include missing from VMs page');
    assert.ok(hostAdapterIndex >= 0, 'shared host adapter include missing from VMs page');
    assert.ok(orderingIndex >= 0, 'shared folder ordering include missing from VMs page');
    assert.ok(lifecycleIndex >= 0, 'VM lifecycle coordinator include missing from VMs page');
    assert.ok(runtimeIndex >= 0, 'vm runtime include missing from VMs page');
    assert.ok(themeTokensCssIndex >= 0, 'shared theme token stylesheet missing from VMs page');
    assert.ok(sharedCssIndex >= 0, 'shared runtime stylesheet missing from VMs page');
    assert.ok(vmCssIndex >= 0, 'vm stylesheet missing from VMs page');
    assert.match(vmPage, /window\.FolderViewPlusFatalRuntimeContext = \{/);
    assert.match(vmPage, /page:\s*'VMs'/);
    assert.match(vmPage, /hostSelector:\s*'#fvplus-vm-runtime-banner-host'/);
    assert.match(vmPage, /<div id="fvplus-vm-runtime-banner-host" aria-live="polite"><\/div>/);
    assert.ok(fatalBannerIndex < contractIndex, 'vm fatal banner must load before folder contract/runtime scripts');
    assert.ok(snapshotIndex < runtimeIndex, 'runtime snapshot client must load before vm.js');
    assert.ok(contractIndex < sharedIndex, 'shared contract must load before shared runtime on VMs page');
    assert.ok(stateObserverIndex < runtimeIndex, 'runtime state observer must load before vm.js');
    assert.ok(hostAdapterIndex < runtimeIndex, 'shared host adapter must load before vm.js');
    assert.ok(hostAdapterIndex < orderingIndex && orderingIndex < runtimeIndex, 'shared ordering must load after the host adapter and before vm.js');
    assert.ok(lifecycleIndex < runtimeIndex, 'VM lifecycle coordinator must load before vm.js');
    assert.ok(sharedIndex < runtimeIndex, 'shared runtime must load before vm.js');
    assert.ok(themeTokensCssIndex < sharedCssIndex, 'theme token stylesheet must load before runtime.shared.css');
    assert.ok(sharedCssIndex < vmCssIndex, 'shared runtime stylesheet must load before vm.css');
});

test('vm runtime uses the shared host adapter for structure, rows, observers, and lifecycle hooks', () => {
    assert.match(runtimeHostAdapterJs, /type: 'vm'/);
    assert.match(runtimeHostAdapterJs, /tableSelector: 'table#kvm_table'/);
    assert.match(vmJs, /const runtimeHostAdapters = window\.FolderViewPlusRuntimeHostAdapters \|\| null;/);
    assert.match(vmJs, /const vmHostAdapter = runtimeHostAdapters\?\.getOrCreate\?\.\('vm'/);
    assert.match(vmJs, /vmHostAdapter\.ensureStructure\(\{/);
    assert.match(vmJs, /vmHostAdapter\.observeRows\(/);
    assert.match(vmJs, /vmHostAdapter\.wrapHook\('loadlist'/);
    assert.match(vmLifecycleJs, /VM_DISPATCH_HOOKS/);
    assert.match(vmLifecycleJs, /hostAdapter\.wrapHook\(hookName/);
    assert.match(vmLifecycleJs, /hostAdapter\.wrapHook\('addVMContext'/);
    assert.match(vmJs, /vmLifecycleApi = vmLifecycleModule\.createApi\(/);
    assert.match(vmJs, /window\.getVmLifecycleDiagnosticsSnapshot =/);
    assert.match(vmJs, /window\.getVmHostAdapterSnapshot =/);
    assert.doesNotMatch(vmJs, /VM_HOST_PAGE_REQUIRED_SELECTORS/);
});

test('vm runtime consumes shared state/perf/action modules and exposes telemetry snapshots', () => {
    assert.match(vmJs, /^\/\/ @ts-check/m);
    assert.match(vmJs, /const runtimeShared = window\.FolderViewDockerRuntimeShared \|\| \{\};/);
    assert.match(vmJs, /const fatalBanner = window\.FolderViewPlusFatalBanner \|\| null;/);
    assert.match(vmJs, /const VM_FATAL_BANNER_HOST_SELECTOR = String\(vmFatalBannerRuntimeConfig\.hostSelector \|\| '#fvplus-vm-runtime-banner-host'\)/);
    assert.match(vmJs, /const createVmRuntimeDiagnosticsBridge = typeof runtimeShared\.createRuntimeDiagnosticsBridge === 'function'/);
    assert.match(vmJs, /vmBootstrapMissingModules\.push\('folderviewplus\.utils\.js'\)/);
    assert.match(vmJs, /vmBootstrapMissingModules\.push\('folderviewplus\.request\.js'\)/);
    assert.match(vmJs, /vmBootstrapMissingModules\.push\('docker\.runtime\.shared\.js'\)/);
    assert.match(vmJs, /const reportVmBootstrapDependencyBanner = \(missingModules\) =>/);
    assert.match(vmJs, /const reportVmFatalRuntimeError = \(error, options = \{\}\) =>/);
    assert.match(vmJs, /const reportVmDegradedRuntimeState = \(error, options = \{\}\) =>/);
    assert.match(vmJs, /const createVmRuntimeRequest = \(url, options = \{\}\) =>/);
    assert.match(vmJs, /FolderView Plus VM runtime bootstrap failed/);
    assert.match(vmJs, /reportVmBootstrapDependencyBanner\(vmBootstrapMissingModules\);/);
    assert.match(vmJs, /const runtimeStateObserverModule = window\.FolderViewPlusRuntimeStateObservers \|\| null;/);
    assert.match(vmJs, /const createRuntimeDebugLogger = typeof runtimeShared\.createDebugLogger === 'function'/);
    assert.match(vmJs, /const vmDebug = createRuntimeDebugLogger\(VM_DEBUG_MODE, 'folderview\.plus vm'\);/);
    assert.match(vmJs, /const vmRuntimeStateStore = createVmRuntimeStateStore\(/);
    assert.match(vmJs, /const vmActionBoundary = createVmAsyncActionBoundary\(/);
    assert.match(vmJs, /const vmSafeUiActionRunner = createVmSafeUiActionRunner\(\);/);
    assert.match(vmJs, /const vmExpandedStateController = runtimeStateObserverModule/);
    assert.match(vmJs, /const vmRuntimeThemeReflowController = runtimeStateObserverModule/);
    assert.match(vmJs, /const applyVmZebra = \(\) => \{/);
    assert.match(vmJs, /const scheduleVmZebraRefresh = \(delayMs = 32\) => \{/);
    assert.match(vmJs, /const adoptVmNativeDetailRows = \(rows = \[\]\) => \{/);
    assert.match(vmJs, /const runVmGuardedAction = async \(actionName, action, context = \{\}\) =>/);
    assert.doesNotMatch(vmJs, /createVmRuntimeCommandCenterController/);
    assert.doesNotMatch(vmJs, /syncVmCommandCenterView/);
    assert.doesNotMatch(vmJs, /data-fvplus-vm-view-mode/);
    assert.doesNotMatch(vmJs, /data-fv-vm-command-action="create-folder"/);
    assert.match(vmJs, /let vmRuntimePerformanceProfile = resolveVmRuntimePerformanceProfile\(/);
    assert.match(vmJs, /window\.getVmRuntimePerfTelemetrySnapshot =/);
    assert.match(vmJs, /window\.getVmRuntimeStateSnapshot =/);
    assert.match(vmJs, /window\.addVMFolderContext = addVMFolderContext;/);
    assert.match(vmJs, /window\.dropDownButton = dropDownButton;/);
    assert.match(vmJs, /window\.editFolder = editFolder;/);
    assert.match(vmJs, /window\.createFolderBtn = createFolderBtn;/);
});

test('vm CSS keeps VM-specific gutter tokens while shared stylesheet owns shared preview and dropdown rules', () => {
    assert.match(vmCss, /--fvplus-vm-folder-right-gutter:\s*18px/);
    assert.match(vmCss, /--fvplus-vm-folder-outer-reserved-width:\s*88px/);
    assert.match(vmCss, /--fvplus-vm-folder-dropdown-right-margin:\s*10px/);
    assert.match(vmCss, /--fvplus-folder-dropdown-right-margin:\s*var\(--fvplus-vm-folder-dropdown-right-margin,\s*10px\)/);
    assert.match(vmCss, /--fvplus-folder-dropdown-icon-size:\s*11px/);
    assert.match(vmCss, /--fvplus-folder-dropdown-radius:\s*5px/);
    assert.match(vmCss, /--fvplus-folder-dropdown-shadow:\s*inset 0 0 0 1px rgba\(255,\s*255,\s*255,\s*0\.05\), 0 1px 3px rgba\(0,\s*0,\s*0,\s*0\.18\)/);
    assert.match(vmCss, /--fvplus-preview-wrapper-margin-top:\s*6px/);
    assert.doesNotMatch(vmCss, /^\.folder-dropdown\s*\{/m);
    assert.match(runtimeSharedCss, /\.folder-preview\s*\{[\s\S]*align-items:\s*center;/);
    assert.match(runtimeSharedCss, /\.folder-preview-wrapper\s*\{[\s\S]*margin-top:\s*var\(--fvplus-preview-wrapper-margin-top,\s*6px\)/);
    assert.match(runtimeSharedCss, /background:\s*var\(--fvplus-folder-dropdown-bg,\s*rgba\(255,\s*154,\s*60,\s*0\.1\)\) !important;/);
    assert.doesNotMatch(runtimeSharedCss, /\.fv-runtime-command-member-dot\s*\{/);
    assert.doesNotMatch(runtimeSharedCss, /\.fv-runtime-command-card\.is-focus-hidden\s*\{/);
});
